// ========================================
// Svenska Läraren - Vocabulary Data
// ========================================

const vocabularyData = {
    niveau2: {
        "Kapitel 10 - Natur & Geografi": [
            { sv: "en natur (er)", fr: "nature, environnement, paysage", ex: "Sveriges natur är mycket vacker." },
            { sv: "en historia (er)", fr: "histoire", ex: "Jag läser om Sveriges historia." },
            { sv: "en ekonomi (er)", fr: "économie", ex: "Landet har en stark ekonomi." },
            { sv: "en halvö (ar)", fr: "péninsule", ex: "Skandinavien är en halvö." },
            { sv: "en del (ar)", fr: "partie", ex: "Stockholm är en del av Sverige." },
            { sv: "ett landskap", fr: "paysage", ex: "Vilket vackert landskap!" },
            { sv: "olika", fr: "différent", ex: "Vi har olika åsikter." },
            { sv: "platta", fr: "plat", ex: "Södra Sverige är ganska platt." },
            { sv: "en kustlinje (er)", fr: "littoral, ligne côtière", ex: "Sverige har en lång kustlinje." },
            { sv: "en sjö (ar)", fr: "lac", ex: "Vi badar i sjön varje sommar." },
            { sv: "en skärgård (ar)", fr: "archipel", ex: "Stockholms skärgård är fantastisk." },
            { sv: "utanför", fr: "hors de, en dehors de, extérieur", ex: "Han väntar utanför dörren." },
            { sv: "en kust (er)", fr: "côte", ex: "Vi bor nära kusten." },
            { sv: "tiotusentals", fr: "dizaines de milliers", ex: "Det finns tiotusentals öar i Sverige." },
            { sv: "Östersjön", fr: "mer baltique", ex: "Östersjön ligger mellan Sverige och Finland." },
            { sv: "en yta", fr: "surface, superficie", ex: "Sveriges yta är 450 000 km²." },
            { sv: "en tredjedel (ar)", fr: "un tiers", ex: "En tredjedel av Sverige är skog." },
            { sv: "en befolkning (ar)", fr: "population" },
            { sv: "egen – eget – egna", fr: "propre (possession)" },
            { sv: "istid", fr: "période glacière" },
            { sv: "i norra", fr: "au nord de" },
            { sv: "i södra", fr: "au sud de" },
            { sv: "i norr", fr: "au nord" },
            { sv: "i söder", fr: "au sud" },
            { sv: "förut", fr: "auparavant, autrefois" },
            { sv: "fattig", fr: "pauvre, misérable, malheureux" },
            { sv: "en invandring (ar)", fr: "immigration" },
            { sv: "en flykting (ar)", fr: "réfugié" },
            { sv: "invandra (1)", fr: "immigrer" },
            { sv: "järn", fr: "fer" },
            { sv: "stål", fr: "acier" },
            { sv: "konstig", fr: "étrange, bizarre" },
            { sv: "en invånare", fr: "habitant" },
            { sv: "rik", fr: "riche" },
            { sv: "Jag kommer inte ihåg precis", fr: "je ne me souviens pas exactement" },
            { sv: "Jag tror att", fr: "je crois que" },
            { sv: "jag antar att", fr: "je suppose que" },
            { sv: "Det var en svår fråga", fr: "C’était une question difficile" },
            { sv: "Vänta, nu måste jag tänka lite", fr: "Attends, je dois un peu y réfléchir" },
            { sv: "Vad heter den/det/de (nu igen)?", fr: "Comment s’appelle (maintenant encore) ?" },
            { sv: "Hur många var det?", fr: "Combien il y en avait-il ?" },
            { sv: "Ja, det stämmer.", fr: "Oui c’est vrai" },
            { sv: "Ja, det är rätt.", fr: "Oui c’est vrai" },
            { sv: "Exakt!", fr: "Exact !" },
            { sv: "Nja, det är inte riktigt rätt.", fr: "Ce n'est pas vraiment correct." },
            { sv: "Nej, det är faktiskt fel.", fr: "C’est en fait faux." },
            { sv: "en författare", fr: "un écrivain" },
            { sv: "en politiker", fr: "un homme politique" },
            { sv: "en diplomat", fr: "un diplomate" },
            { sv: "en vetenskapsman", fr: "scientifique" },
            { sv: "en uppfinnare", fr: "inventeur" },
            { sv: "en popstjärna", fr: "pop star" },
            { sv: "en regissör (er)", fr: "réalisateur" },
            { sv: "en skådespelare / skådespelerska", fr: "acteur" },
            { sv: "ett helgon", fr: "saint" },
            { sv: "en idrottare", fr: "sportif" },
            { sv: "en operasångare / operasångerska", fr: "chanteur d’opéra" },
            { sv: "en drottning (ar)", fr: "reine" },
            { sv: "en utlänning (ar)", fr: "étranger" },
            { sv: "gullig", fr: "mignon, sympa" },
            { sv: "en flod (er)", fr: "fleuve, rivière" },
            { sv: "ett berg", fr: "montagne, mont" }
        ],
        "Kapitel 11 - Rencontres": [
            { sv: "En idé är att", fr: "une idée est de" },
            { sv: "Man kan prova att", fr: "On peut essayer de" },
            { sv: "Det bästa är kanske att...", fr: "Le mieux serait peut-être de" },
            { sv: "Där/Då kan man", fr: "Là/alors on peut" },
            { sv: "Ett bra sätt är att", fr: "Un bon moyen est de" },
            { sv: "gå ut med en hund", fr: "sortir le chien" },
            { sv: "ensam", fr: "seul" },
            { sv: "tipsa (1), rekommendera (1)", fr: "conseiller" },
            { sv: "stilig", fr: "beau, chic" },
            { sv: "ett tips", fr: "conseil" },
            { sv: "ett svar", fr: "réponse" },
            { sv: "ganska många", fr: "plutôt beaucoup" },
            { sv: "en dejtingsajt (er)", fr: "application de rencontres" },
            { sv: "lära sig (3)", fr: "apprendre" },
            { sv: "barnfri", fr: "sans enfants" },
            { sv: "härlig", fr: "magnifique" },
            { sv: "kul", fr: "cool" },
            { sv: "duktig i köket", fr: "doué en cuisine" },
            { sv: "X är inget för mig", fr: "X n’est pas pour moi" },
            { sv: "en rad (er)", fr: "ligne, rangée" },
            { sv: "ett meddelande", fr: "message" },
            { sv: "inte heller", fr: "pas non plus" },
            { sv: "en kram (ar)", fr: "câlin, étreinte" },
            { sv: "en sporthatare", fr: "qqn qui déteste le sport" },
            { sv: "en gård", fr: "une ferme" },
            { sv: "ett djur", fr: "animal" },
            { sv: "hit", fr: "ici (mouvement)" },
            { sv: "frånskild", fr: "séparé, divorcé" },
            { sv: "varannan", fr: "alterné, un sur deux" },
            { sv: "tvätta (1)", fr: "faire la lessive" },
            { sv: "stryka (stryker, strök, strukit)", fr: "repasser" },
            { sv: "leka (2)", fr: "jouer" },
            { sv: "förstås", fr: "bien entendu, évidemment" },
            { sv: "ett kök", fr: "cuisine (pièce)" },
            { sv: "nästa sommar", fr: "été prochain" },
            { sv: "Jag tycker om (att)…", fr: "J’aime..." },
            { sv: "Jag också/Det gör inter jag", fr: "Moi aussi/Moi pas" },
            { sv: "Jag kan…", fr: "Je peux..." },
            { sv: "Jag också/Det kan inte jag", fr: "Moi aussi/Moi pas" },
            { sv: "Jag tycker inte om (att) …", fr: "Je n’aime pas…" },
            { sv: "Inte jag heller/men det gör jag", fr: "Moi non plus/Moi si" },
            { sv: "Jan kan inte…", fr: "Je ne peux pas…" },
            { sv: "Inte jag heller/Men det kan jag", fr: "Moi non plus/Moi si" },
            { sv: "huslig", fr: "casanier" },
            { sv: "äventyrlig", fr: "aventurier" },
            { sv: "trevlig", fr: "sympa" },
            { sv: "arbetslös", fr: "sans emploi" },
            { sv: "manlig", fr: "viril" },
            { sv: "rolig", fr: "drôle" },
            { sv: "ointressant", fr: "inintéressant" },
            { sv: "töntig", fr: "stupide" },
            { sv: "tråkig", fr: "ennuyant" },
            { sv: "smart/klok/intelligent", fr: "intelligent" },
            { sv: "Det tycker jag också", fr: "Je pense aussi" },
            { sv: "Ja, han är perfekt!", fr: "Oui, c’est parfait" },
            { sv: "Absolut!", fr: "Absolument !" },
            { sv: "Bra idé", fr: "Bonne idée !" },
            { sv: "Jag håller med", fr: "Je suis d’accord" },
            { sv: "Nej, det tycker inte jag heller", fr: "Non, je ne pense pas non plus" },
            { sv: "Inte jag heller", fr: "Moi non plus" },
            { sv: "Ja, kanske, men är inte … bättre?", fr: "Oui, peut-être, mais…n'est pas mieux?" },
            { sv: "Nja, jag vet inte. Men … verkar bättre!", fr: "Eh bien, je ne sais pas. Mais ... semble mieux!" },
            { sv: "Va! Tycker du? Jag tycker att…", fr: "Tu crois/trouves? Je pense que…" },
            { sv: "ett tangentbord", fr: "clavier" },
            { sv: "en papperskorg (ar)", fr: "corbeille" },
            { sv: "en sladd (ar)/kabel (ar)", fr: "câble" },
            { sv: "kursiv stil", fr: "italique" },
            { sv: "spara (1)", fr: "sauvegarder" },
            { sv: "skriv ut", fr: "imprimer" },
            { sv: "ett snabel-a", fr: "@" },
            { sv: "en mapp (ar)", fr: "dossier" },
            { sv: "fet stil", fr: "gras" },
            { sv: "ett bindestreck", fr: "trait d’union" },
            { sv: "ångra (1)", fr: "annuler (regretter)" },
            { sv: "bifoga (1)", fr: "joindre (fichier)" },
            { sv: "en mus (möss, mössen)", fr: "souris" },
            { sv: "en punkt (er)", fr: "point" },
            { sv: "ett understreck", fr: "tiret bas/underscore" },
            { sv: "en skärm (ar)", fr: "écran" },
            { sv: "öppna (1)", fr: "ouvrir" },
            { sv: "ett utropstecken", fr: "point d’exclamation" },
            { sv: "ett frågetecken", fr: "point d’interrogation" },
            { sv: "ett snedstreck", fr: "slash" },
            { sv: "ett typsnitt", fr: "police (typographie)" },
            { sv: "söka (2)", fr: "chercher" },
            { sv: "klicka (1)", fr: "cliquer" },
            { sv: "logga in (1)", fr: "se connecter" },
            { sv: "ett virus", fr: "virus" },
            { sv: "ett lösenord", fr: "mot de passe" },
            { sv: "koppla (1)", fr: "brancher" },
            { sv: "sätta på", fr: "allumer" },
            { sv: "starta om (1)", fr: "redémarrer" },
            { sv: "en länk (ar)", fr: "un lien" },
            { sv: "fungera (1)", fr: "fonctionner" },
            { sv: "fylla på (2)", fr: "remplir, remettre (papier)" },
            { sv: "en hårddisk (ar)", fr: "disque dur" },
            { sv: "stänga av (1)", fr: "fermer, éteindre" },
            { sv: "ladda ner (1)", fr: "télécharger" },
            { sv: "stoppa in (1)", fr: "introduire, mettre" },
            { sv: "trasig", fr: "cassé, défectueux, pété" },
            { sv: "krascha (1)", fr: "planter (ordinateur)" },
            { sv: "en skrivare", fr: "imprimante" }
        ],
        "Kapitel 12 - Mat": [
            { sv: "en råvara", fr: "ingrédient" },
            { sv: "en vardagsmat", fr: "plat quotidien" },
            { sv: "en växt (er)", fr: "plante" },
            { sv: "dill", fr: "aneth" },
            { sv: "ett brännvin", fr: "eau-de-vie" },
            { sv: "en råg", fr: "seigle" },
            { sv: "ett nötkött", fr: "bœuf" },
            { sv: "en gryta", fr: "ragoût" },
            { sv: "inlagd i ättika", fr: "mariné dans le vinaigre" },
            { sv: "en lukt (er)", fr: "odeur" },
            { sv: "en smak (er)", fr: "goût, saveur" },
            { sv: "en lax (ar)", fr: "saumon" },
            { sv: "jordgubbar", fr: "fraises" },
            { sv: "en undersökning (ar)", fr: "sondage, enquête" },
            { sv: "få personer", fr: "quelques personnes" },
            { sv: "tillräcklig", fr: "suffisant, suffisamment" },
            { sv: "flesta", fr: "le plus" },
            { sv: "mörk choklad", fr: "chocolat noir" },
            { sv: "mjölkchoklad", fr: "chocolat au lait" },
            { sv: "en lök (ar)", fr: "oignon" },
            { sv: "pytt i panna", fr: "poêlée" },
            { sv: "kåldolmar", fr: "choux farcis" },
            { sv: "småkakor", fr: "petits biscuits" },
            { sv: "bjuda (bjuder, bjöd, bjudit)", fr: "inviter" },
            { sv: "fräsch", fr: "frais" },
            { sv: "en sparris (ar)", fr: "asperge" },
            { sv: "Det är fel att", fr: "Ce n’est pas bien de" },
            { sv: "en snabbmat", fr: "fast-food" },
            { sv: "På väg hem från", fr: "sur le chemin du retour de" },
            { sv: "en svamp (ar)", fr: "champignon" },
            { sv: "Jag är sugen på", fr: "J’ai envie de" },
            { sv: "skicka saltet (1)", fr: "passer le sel" },
            { sv: "smaka (1)", fr: "goûter, être bon" }
        ],
        "Kapitel 13 - Arbete": [
            { sv: "verka (1)", fr: "sembler, paraître" },
            { sv: "en kändis (ar)", fr: "célébrité" },
            { sv: "en översättare", fr: "traducteur" },
            { sv: "ledig", fr: "libre" },
            { sv: "stressig", fr: "stressant" },
            { sv: "är tvungen", fr: "être obligé de" },
            { sv: "skynda sig (1)", fr: "se dépêcher" },
            { sv: "duka (1)", fr: "mettre la table" },
            { sv: "ringa på dörren (2)", fr: "sonner à la porte" },
            { sv: "samtidigt", fr: "au même moment" },
            { sv: "toppjobb", fr: "poste clé" },
            { sv: "läkemedel", fr: "médicament" },
            { sv: "hämta (1)", fr: "aller chercher" },
            { sv: "lämna (1)", fr: "quitter, laisser, déposer" },
            { sv: "förskola", fr: "école maternelle" },
            { sv: "hushållsarbete", fr: "ménage" },
            { sv: "segla (1)", fr: "faire de la voile" },
            { sv: "försova sig", fr: "dormir trop longtemps, ne pas entendre son réveil" },
            { sv: "en affärsman", fr: "un homme d’affaires" },
            { sv: "var tvungen att", fr: "devoir (=måste)" },
            { sv: "ett möte", fr: "une réunion" },
            { sv: "ett labb", fr: "un laboratoire" },
            { sv: "hämtmat", fr: "plats à emporter" },
            { sv: "en gäst (er)", fr: "un hôte, un invité" },
            { sv: "ett huvudkontor", fr: "maison mère" },
            { sv: "viktig", fr: "important" },
            { sv: "ligga på topp", fr: "avoir un poste clé" },
            { sv: "vakna (1) / stiga (steg) upp", fr: "s’éveiller / se lever" },
            { sv: "gå och lägga sig", fr: "aller se coucher" },
            { sv: "en flygvärdinna", fr: "une hôtesse de l’air" },
            { sv: "landa (1)", fr: "atterrir" },
            { sv: "en pilot (-er)", fr: "pilote" },
            { sv: "ett (flyg)plan", fr: "un avion" },
            { sv: "servera (1)", fr: "servir" },
            { sv: "svara (1)", fr: "répondre" },
            { sv: "lyssna (1)", fr: "écouter" },
            { sv: "sitta och prata", fr: "être assis et parler" },
            { sv: "leka (2)", fr: "jouer (enfants)" },
            { sv: "läsa serier", fr: "lire des bandes dessinées" },
            { sv: "spela schack / damspel", fr: "jouer aux échecs/dames" },
            { sv: "ta ett bad", fr: "prendre un bain" },
            { sv: "somna (1)", fr: "s’endormir" },
            { sv: "sova (sover, sov, sovit)", fr: "dormir" },
            { sv: "skratta (1)", fr: "rire" },
            { sv: "ett bröllop", fr: "un mariage" },
            { sv: "en guide (er)", fr: "un guide touristique" },
            { sv: "en barnvakt (er)", fr: "baby-sitter" },
            { sv: "en simlärare", fr: "professeur de natation" },
            { sv: "simma (1)", fr: "nager" },
            { sv: "en snickare", fr: "un menuisier" },
            { sv: "en målare", fr: "un peintre" },
            { sv: "en trädgårdsmästare", fr: "jardinier" },
            { sv: "en fotograf (er)", fr: "photographe" },
            { sv: "en arkitekt (er)", fr: "architecte" },
            { sv: "en sjuksköterska", fr: "infirmière" },
            { sv: "en personlig tränare", fr: "coach personnel" },
            { sv: "en taxichaufför (er)", fr: "conducteur de taxi" },
            { sv: "en datasupporttekniker", fr: "informaticien" },
            { sv: "en bilmekaniker", fr: "mécanicien" },
            { sv: "händig", fr: "habile" },
            { sv: "modig", fr: "courageux" },
            { sv: "duktig på", fr: "bon en quelque chose" },
            { sv: "noggrann", fr: "minutieux, soigneux" },
            { sv: "omtänksam", fr: "attentif aux autres" },
            { sv: "stark", fr: "fort" },
            { sv: "teknisk", fr: "technique" },
            { sv: "pedagogisk", fr: "pédagogique" },
            { sv: "kreativ", fr: "créatif" },
            { sv: "social", fr: "social" },
            { sv: "trevlig", fr: "agréable, plaisant" },
            { sv: "ett körkort", fr: "un permis de conduire" },
            { sv: "fixa (1)", fr: "arranger, réparer" },
            { sv: "en idrott/sport", fr: "sport" },
            { sv: "en vetenskap", fr: "science" },
            { sv: "fota/fotografera", fr: "photo" },
            { sv: "naturligtvis", fr: "naturellement, bien entendu" }
        ],
        "Kapitel 14 - Fritid": [
            { sv: "utsikt över", fr: "avec vue sur" },
            { sv: "i gräset", fr: "dans l’herbe" },
            { sv: "en vila", fr: "repos" },
            { sv: "en frihet (er)", fr: "liberté" },
            { sv: "grilla (1)", fr: "faire un barbecue" },
            { sv: "åka båt (2)", fr: "faire du bateau" },
            { sv: "gå barfota", fr: "marcher pieds nus" },
            { sv: "plocka bär och svamp", fr: "cueillir des baies et des champignons" },
            { sv: "sola och bada (1)", fr: "bronzer et se baigner" },
            { sv: "vila (1)", fr: "se reposer" },
            { sv: "vara själv med familjen", fr: "être avec sa famille" },
            { sv: "spela kort med familjen", fr: "jouer aux cartes en famille" },
            { sv: "renovera huset (2)", fr: "rénover la maison" },
            { sv: "klippa gräs (2)", fr: "tondre" },
            { sv: "hugga ved", fr: "couper du bois" },
            { sv: "ha släktingar på långa besök", fr: "recevoir la famille pour de longs séjours" },
            { sv: "äta filmjölk och blåbär", fr: "manger du lait caillé et des myrtilles" },
            { sv: "jobbig", fr: "pénible" },
            { sv: "ett landställe", fr: "maison de campagne" },
            { sv: "äga", fr: "posséder, avoir" },
            { sv: "vanlig", fr: "habituel, ordinaire" },
            { sv: "jobba vid datorn", fr: "travailler sur le pc" },
            { sv: "undra om (1)", fr: "se demander si" },
            { sv: "en (bil)-färja", fr: "Ferry" },
            { sv: "en mås (ar)", fr: "mouette" },
            { sv: "ett grus", fr: "gravier, sable" },
            { sv: "glittra (1)", fr: "briller, étinceler" },
            { sv: "kliva ur bilen", fr: "sortir de la voiture" },
            { sv: "ett hjärta", fr: "cœur" },
            { sv: "skål", fr: "santé (boire)" },
            { sv: "ett dass", fr: "toilette" },
            { sv: "få lite ont i", fr: "ressentir une douleur à" },
            { sv: "lukta (1)", fr: "sentir (odeur)" },
            { sv: "sur", fr: "fâché, contrarié, sur" },
            { sv: "en paj (er)", fr: "tarte" },
            { sv: "en bastu (-r)", fr: "sauna" },
            { sv: "nervös", fr: "nerveux" },
            { sv: "lätt", fr: "facile, léger" },
            { sv: "tack för senast", fr: "merci pour la dernière fois" },
            { sv: "ta bort", fr: "enlever" },
            { sv: "behöver inte", fr: "ne pas devoir (måste inte)" },
            { sv: "ett bröllop", fr: "mariage" },
            { sv: "ett kalas", fr: "fête" },
            { sv: "en inflyttningsfest (er)", fr: "pendaison de crémaillère" },
            { sv: "Vi fixar", fr: "on s’occupe de" },
            { sv: "vi tänder grillarna", fr: "on allume le barbecue" },
            { sv: "en vigsel (ar)", fr: "cérémonie de mariage, noces" },
            { sv: "en önskelista", fr: "liste des cadeaux de mariage" },
            { sv: "tack för ikväll", fr: "merci pour ce soir" },
            { sv: "Ta för er!", fr: "Servez-vous" },
            { sv: "Det är bra för mig", fr: "J’ai assez merci" },
            { sv: "va?", fr: "N’est-ce pas ?" }
        ],
        "Kapitel 15 - Livsstil": [
            { sv: "skämta (1)", fr: "plaisanter, blaguer" },
            { sv: "kalla (1)", fr: "appeler, nommer" },
            { sv: "heter … i efternamn", fr: "avoir … pour nom de famille" },
            { sv: "hälften av", fr: "la moitié de" },
            { sv: "ett par", fr: "couple" },
            { sv: "i veckan", fr: "par semaine" },
            { sv: "tjock", fr: "gros, épais" },
            { sv: "jag minns inte", fr: "je ne me rappelle pas" },
            { sv: "Varför då?", fr: "Pourquoi donc ?" },
            { sv: "tyst", fr: "silencieux" },
            { sv: "ett prat", fr: "conversation" },
            { sv: "vandra (1)", fr: "se promener, faire une randonnée" },
            { sv: "ett mål", fr: "but, objectif" },
            { sv: "en by (ar)", fr: "village" },
            { sv: "verkar vara", fr: "semble être" },
            { sv: "en sten (ar)", fr: "pierre" },
            { sv: "ensamma", fr: "seul" },
            { sv: "en bit (ar)", fr: "morceau, partie" },
            { sv: "från dag till dag", fr: "d’un jour à l’autre" },
            { sv: "ett mörk", fr: "obscurité" },
            { sv: "innan", fr: "avant (que)" },
            { sv: "deppig", fr: "déprimé" },
            { sv: "fulla av", fr: "rempli de" },
            { sv: "verka (1)", fr: "sembler" },
            { sv: "ingen/någon", fr: "personne, quelqu’un" },
            { sv: "inget/något", fr: "rien, quelque chose" },
            { sv: "fast", fr: "bien que" },
            { sv: "Det beror på", fr: "Cela dépend de" },
            { sv: "betyda (2)", fr: "signifier" },
            { sv: "en kropp (ar)", fr: "corps" },
            { sv: "bomull", fr: "coton" },
            { sv: "ull", fr: "laine" },
            { sv: "tunn", fr: "mince, fin" },
            { sv: "räcker", fr: "suffire" },
            { sv: "en svett", fr: "sueur" },
            { sv: "skydda (1)", fr: "protéger" },
            { sv: "röra (3)", fr: "bouger" },
            { sv: "torr", fr: "sec" },
            { sv: "en vante (vantar)", fr: "gant" }
        ],
        "Kapitel 16 - Skola & Utbildning": [
            { sv: "ett lov", fr: "congé" },
            { sv: "en termin (er)", fr: "semestre, trimestre" },
            { sv: "en föreläsning (ar)", fr: "cours magistral" },
            { sv: "en rast (er)", fr: "pause" },
            { sv: "ett seminarium", fr: "séminaire" },
            { sv: "en grundskola", fr: "école primaire" },
            { sv: "gymnasiet", fr: "lycée" },
            { sv: "ett universitet", fr: "université" },
            { sv: "Komvux", fr: "promotion sociale" },
            { sv: "ett betyg", fr: "note, évaluation" },
            { sv: "ett ämne", fr: "matière (scolaire)" },
            { sv: "1 till 9", fr: "1 à 9" },
            { sv: "en väg (ar)", fr: "chemin" },
            { sv: "en utbildning (ar)", fr: "éducation, enseignement" },
            { sv: "en plugghäst (ar)", fr: "tête, personne intelligente" },
            { sv: "fokusera (1)", fr: "se concentrer" },
            { sv: "duktig", fr: "bon, capable" },
            { sv: "skolka (1)", fr: "sécher les cours" },
            { sv: "räkna (1)", fr: "compter" },
            { sv: "småtråkig", fr: "un peu ennuyeux" },
            { sv: "är färdig med", fr: "en avoir fini avec" },
            { sv: "en gata", fr: "rue" },
            { sv: "en andra chans", fr: "une seconde chance" },
            { sv: "framtiden", fr: "l'avenir" },
            { sv: "ett fast jobb", fr: "emploi fixe" },
            { sv: "forska (1)", fr: "faire de la recherche" },
            { sv: "en praktik (er)", fr: "stage" },
            { sv: "om + temps", fr: "dans X temps" },
            { sv: "då", fr: "alors, à ce moment-là" },
            { sv: "först", fr: "d'abord" },
            { sv: "sedan", fr: "ensuite" },
            { sv: "efter det", fr: "ensuite" },
            { sv: "vara färdig med något", fr: "avoir terminé quelque chose" },
            { sv: "fortsätta", fr: "continuer" },
            { sv: "söka (2) (efter/till)", fr: "chercher/postuler" },
            { sv: "leta (1) efter", fr: "chercher pour trouver" },
            { sv: "hitta (1)", fr: "trouver" },
            { sv: "frilansa (1)", fr: "travailler en freelance" },
            { sv: "examen", fr: "diplôme" },
            { sv: "börsmäklare", fr: "courtier, trader" },
            { sv: "tuff", fr: "dur, difficile" }
        ],

        "Moodle & Textes": [
            { sv: "inte längre = inte mer", fr: "ne… plus" },
            { sv: "hända (händer, hände, hänt)", fr: "se passer, arriver" },
            { sv: "medan", fr: "pendant que" },
            { sv: "bege sig", fr: "se rendre" },
            { sv: "rak (raka vägen)", fr: "Droit (le droit chemin)" },
            { sv: "en matros (-er)", fr: "un matelot" },
            { sv: "en panna (-or)", fr: "un front (aussi poêle)" },
            { sv: "en apa (apor)", fr: "un singe" },
            { sv: "en kappsäck", fr: "un sac de voyage" },
            { sv: "full med", fr: "rempli de" },
            { sv: "guldpengar", fr: "pièces d’or" },
            { sv: "stadig", fr: "solide, ferme" },
            { sv: "gå stadigt", fr: "marcher d’un pas ferme" },
            { sv: "utan att", fr: "sans (faire quelque chose)" },
            { sv: "vända sig om", fr: "se retourner" },
            { sv: "märkvärdig", fr: "remarquable, étrange" },
            { sv: "en tår", fr: "une larme" },
            { sv: "stark", fr: "fort" },
            { sv: "en polis (-er)", fr: "un policier" },
            { sv: "lyfta (2)", fr: "soulever" },
            { sv: "en häst (-ar)", fr: "un cheval" },
            { sv: "utan vidare", fr: "sans plus, tout bonnement" },
            { sv: "ett fritidshus / sommarstuga", fr: "maison de campagne" },
            { sv: "utsikt över", fr: "vue sur" },
            { sv: "hav (-et)", fr: "mer" },
            { sv: "granne (-n, -ar)", fr: "voisin" },
            { sv: "gå barfota", fr: "marcher à pieds nus" },
            { sv: "en vila", fr: "repos" },
            { sv: "glad", fr: "content, joyeux" },
            { sv: "lycklig", fr: "heureux" },
            { sv: "på landet", fr: "à la campagne" },
            { sv: "hugga ved", fr: "couper du bois" },
            { sv: "en släkting", fr: "parent" },
            { sv: "stanna (1)", fr: "rester" },
            { sv: "bråka (1)", fr: "se disputer" },
            { sv: "ett läge", fr: "situation" },
            { sv: "uteplats", fr: "terrasse" },
            { sv: "avstånd", fr: "distance" },
            { sv: "en inbjudan", fr: "une invitation" },
            { sv: "ännu", fr: "encore" },
            { sv: "undra (1)", fr: "demander" },
            { sv: "lakan", fr: "draps" },
            { sv: "titta efter", fr: "chercher du regard" },
            { sv: "skrika (skriker, skrek, skrikit)", fr: "crier" },
            { sv: "kvar", fr: "qui reste" },
            { sv: "färjeläge", fr: "embarcadère" },
            { sv: "grusväg", fr: "chemin de terre" },
            { sv: "glittra (1)", fr: "scintiller" },
            { sv: "ur", fr: "hors de" },
            { sv: "ett dass", fr: "toilette sèche" },
            { sv: "tvätta sig", fr: "se laver" },
            { sv: "snöre", fr: "cordon" },
            { sv: "dra (drar, drog, dragit)", fr: "tirer" },
            { sv: "ont", fr: "mal" },
            { sv: "kantarell", fr: "chanterelle" },
            { sv: "ställe", fr: "endroit" },
            { sv: "sur", fr: "fâché" },
            { sv: "älgstek", fr: "rôti d’élan" },
            { sv: "skjuta (skjuter, sköt, skjutit)", fr: "tirer (arme)" },
            { sv: "frysa (fryser, frös, frusit)", fr: "geler" },
            { sv: "naken", fr: "nu" },
            { sv: "smulpaj", fr: "crumble" },
            { sv: "vetemjöl", fr: "farine de blé" },
            { sv: "matsked", fr: "cuiller à soupe" },
            { sv: "potatismjöl", fr: "fécule" },
            { sv: "blanda (1)", fr: "mélanger" },
            { sv: "en skål", fr: "saladier" },
            { sv: "en form", fr: "moule" },
            { sv: "en deg", fr: "pâte" },
            { sv: "ljummen", fr: "tiède" },
            { sv: "grädda (1)", fr: "cuire au four" },
            { sv: "en ugn", fr: "four" },
            { sv: "en klänning", fr: "robe" },
            { sv: "före", fr: "avant" },
            { sv: "glömma (2)", fr: "oublier" },
            { sv: "dra hemåt", fr: "rentrer chez soi" },
            { sv: "vett och etikett", fr: "code de bonne conduite" },
            { sv: "bjuden på", fr: "invité à" },
            { sv: "ytterskor", fr: "chaussures d’extérieur" },
            { sv: "inneskor", fr: "chaussures d’intérieur" },
            { sv: "ta på / ta av", fr: "mettre / retirer (vêtements)" },
            { sv: "knytis", fr: "auberge espagnole" },
            { sv: "tända (2)", fr: "allumer" },
            { sv: "brännboll", fr: "jeu de balle suédois" },
            { sv: "mot", fr: "contre/vers" },
            { sv: "vigsel", fr: "bénédiction" },
            { sv: "äga rum", fr: "avoir lieu" },
            { sv: "danssko", fr: "chaussure de danse" },
            { sv: "nyfödd", fr: "nouveau-né" },
            { sv: "gammpojken", fr: "vieux garçon" },
            { sv: "förr", fr: "autrefois" },
            { sv: "växa upp", fr: "grandir" },
            { sv: "sluttning", fr: "pente" },
            { sv: "trähus", fr: "maison de bois" },
            { sv: "förvånad", fr: "étonné" },
            { sv: "i alla fall", fr: "en tous cas" },
            { sv: "ett moln", fr: "nuage" },
            { sv: "sväva (1)", fr: "planer" },
            { sv: "en trappa", fr: "escalier" },
            { sv: "ett dragspel", fr: "accordéon" },
            { sv: "känna sig", fr: "se sentir" },
            { sv: "tung / lätt", fr: "lourd / léger" },
            { sv: "ett öde", fr: "destin" },
            { sv: "hustru", fr: "épouse" },
            { sv: "lycka", fr: "bonheur" },
            { sv: "vemodig", fr: "mélancolique" },
            { sv: "braka loss", fr: "se mettre à barder" },
            { sv: "buller", fr: "vacarme" },
            { sv: "vrål", fr: "hurlement" },
            { sv: "brödkavel", fr: "rouleau à pâtisserie" },
            { sv: "odugling", fr: "incapable" },
            { sv: "latmask", fr: "fainéant" },
            { sv: "suput", fr: "ivrogne" },
            { sv: "helst", fr: "de préférence" },
            { sv: "dö på fläcken", fr: "mourir sur place" },
            { sv: "blind", fr: "aveugle" },
            { sv: "fly (3)", fr: "fuir" },
            { sv: "rida", fr: "chevaucher" },
            { sv: "enligt", fr: "selon" },
            { sv: "egentligen", fr: "en fait" },
            { sv: "skilja sig", fr: "se séparer" },
            { sv: "vård", fr: "soins" },
            { sv: "kaka", fr: "gâteau" },
            { sv: "bulle", fr: "brioche" },
            { sv: "snacka (1)", fr: "bavarder" },
            { sv: "mest", fr: "surtout" },
            { sv: "ägg", fr: "oeuf" },
            { sv: "vara dubbelbokad", fr: "avoir un conflit horaire" },
            { sv: "söka någon", fr: "chercher à atteindre quelqu’un" },
            { sv: "försäkringskassa", fr: "mutuelle" },
            { sv: "föräldrapenning", fr: "allocations familiales" },
            { sv: "tanke", fr: "pensée" },
            { sv: "märka (2)", fr: "remarquer" },
            { sv: "prat", fr: "bavardage" },
            { sv: "småprata", fr: "parler de tout et de rien" },
            { sv: "medlem", fr: "membre" },
            { sv: "skön", fr: "agréable" },
            { sv: "nicka (1)", fr: "approuver" },
            { sv: "klättra (1)", fr: "grimper" },
            { sv: "berg", fr: "montagne" },
            { sv: "verka (1)", fr: "sembler" },
            { sv: "nöjd", fr: "content" },
            { sv: "en bit ifrån", fr: "à une certaine distance" },
            { sv: "ljus", fr: "lumière" },
            { sv: "mörker", fr: "obscurité" },
            { sv: "längta efter", fr: "avoir très envie de" },
            { sv: "sucka (1)", fr: "soupirer" },
            { sv: "gå mot", fr: "aller vers" },
            { sv: "midsommar", fr: "solstice d’été" },
            { sv: "verkligen", fr: "vraiment" },
            { sv: "hoppas", fr: "espérer" },
            { sv: "deppig av", fr: "déprimé" },
            { sv: "siffra", fr: "chiffre" },
            { sv: "använda", fr: "utiliser" },
            { sv: "personnummer", fr: "numéro national" },
            { sv: "badplats", fr: "lieu de baignade" },
            { sv: "beställa (2)", fr: "commander" },
            { sv: "både och", fr: "les deux à la fois" },
            { sv: "dygn", fr: "24h" },
            { sv: "mild", fr: "doux" },
            { sv: "bero på", fr: "dépendre de" },
            { sv: "ostadig", fr: "instable" },
            { sv: "påstående", fr: "affirmation" },
            { sv: "lager", fr: "couche" },
            { sv: "springa", fr: "courir" },
            { sv: "svettig", fr: "en sueur" },
            { sv: "stilla", fr: "tranquille" },
            { sv: "fot", fr: "pied" },
            { sv: "hand", fr: "main" },
            { sv: "huvud", fr: "tête" },
            { sv: "mage", fr: "ventre" },
            { sv: "rumpa", fr: "postérieur" },
            { sv: "svettas", fr: "transpirer" },
            { sv: "mössa", fr: "bonnet" },
            { sv: "minnas / komma ihåg", fr: "se souvenir" },
            { sv: "föremål", fr: "objet" },
            { sv: "lekställning", fr: "portique de jeux" },
            { sv: "rutschbana", fr: "toboggan" },
            { sv: "studsmatta", fr: "trampoline" },
            { sv: "leksak", fr: "jouet" },
            { sv: "gå sönder", fr: "se casser" },
            { sv: "bänk", fr: "banc" },
            { sv: "väntsal", fr: "salle d’attente" },
            { sv: "julgran", fr: "sapin de noël" },
            { sv: "juldag", fr: "jour de noël" },
            { sv: "anslagstavla", fr: "tableau d’affichage" },
            { sv: "försenad", fr: "en retard" },
            { sv: "inställd", fr: "annulé" },
            { sv: "trist / sorglig", fr: "triste (événement)" },
            { sv: "ledsen", fr: "triste (personne)" },
            { sv: "åker", fr: "champ" },
            { sv: "yxa", fr: "hache" },
            { sv: "döda (1)", fr: "tuer" },
            { sv: "Godkänd", fr: "Approuvé, réussi" },
            { sv: "Välja", fr: "Choisir" },
            { sv: "Populär", fr: "Apprécié" },
            { sv: "Fordon", fr: "Véhicule" },
            { sv: "Vanlig >< ovanlig", fr: "Courant >< rare" },
            { sv: "Låna (1)", fr: "Emprunter" },
            { sv: "Låna ut", fr: "Prêter" },
            { sv: "Lån", fr: "Emprunt" },
            { sv: "Examen", fr: "Examen final" },
            { sv: "pluggis", fr: "bûcheur" },
            { sv: "lära", fr: "apprendre (à qqn)" },
            { sv: "lära sig", fr: "apprendre (à soi)" },
            { sv: "tonåring", fr: "adolescent" },
            { sv: "matte", fr: "math" },
            { sv: "samhällskunskap", fr: "sciences sociales" },
            { sv: "trivas", fr: "se plaire" },
            { sv: "sträng", fr: "sévère" },
            { sv: "ta studenten", fr: "passer l'examen final" },
            { sv: "vara sugen på", fr: "avoir très envie de" },
            { sv: "masterexamen", fr: "diplôme de master" },
            { sv: "gå ut nian", fr: "terminer la 9ème" },
            { sv: "hoppa av", fr: "arrêter en cours" },
            { sv: "verkstad", fr: "atelier" },
            { sv: "läsa in", fr: "rattraper" },
            { sv: "andra", fr: "deuxième" },
            { sv: "värst", fr: "pire" },
            { sv: "fiskkorv", fr: "saucisse de poisson" },
            { sv: "blek", fr: "pâle" },
            { sv: "se ut som", fr: "ressembler à" },
            { sv: "mos", fr: "purée" },
            { sv: "hitta på", fr: "inventer" },
            { sv: "påhitt", fr: "invention" },
            { sv: "matpåhitt", fr: "créations culinaires" },
            { sv: "se dagens ljus", fr: "voir le jour" },
            { sv: "för övrigt", fr: "par ailleurs" },
            { sv: "tant", fr: "dame" },
            { sv: "mattant", fr: "dame de cantine" },
            { sv: "tvinga (1)", fr: "forcer" },
            { sv: "äta upp", fr: "finir son assiette" },
            { sv: "utveckla (1)", fr: "développer" },
            { sv: "spotta (1)", fr: "cracher" },
            { sv: "märkas", fr: "se remarquer" },
            { sv: "ficka", fr: "poche" },
            { sv: "följd", fr: "conséquence" },
            { sv: "lukt", fr: "odeur" },
            { sv: "följa med", fr: "accompagner" },
            { sv: "plåga", fr: "peine, torture" },
            { sv: "i stort sett", fr: "en gros" },
            { sv: "ätare", fr: "mangeur" },
            { sv: "välja", fr: "choisir" },
            { sv: "vara ensam om", fr: "être le seul à" },
            { sv: "eftermiddagshem", fr: "garderie" },
            { sv: "ordna (1)", fr: "organiser" },
            { sv: "enbart", fr: "seulement" },
            { sv: "ung", fr: "jeune" },
            { sv: "hata (1)", fr: "détester" },
            { sv: "messmör", fr: "pâte à tartiner au petit lait" }
        ],
        "Livre d'exercices": [
            { sv: "Jag har mycket att göra", fr: "j’ai beaucoup à faire" },
            { sv: "ett prov", fr: "examen" },
            { sv: "pigg", fr: "actif, en forme" },
            { sv: "en fiol", fr: "violon" },
            { sv: "vacker", fr: "beau" },
            { sv: "sätta på", fr: "se mettre à son ordinateur" },
            { sv: "trött på", fr: "fatigué de" },
            { sv: "sitter vid datorn", fr: "être devant le pc" },
            { sv: "bjuda på", fr: "inviter à" },
            { sv: "dricka till maten", fr: "boire avec le repas" },
            { sv: "annorlunda", fr: "autrement, différent" },
            { sv: "en grädde", fr: "crème fraîche" },
            { sv: "bara", fr: "seulement, juste" },
            { sv: "en åsikt", fr: "opinion" },
            { sv: "en värdering", fr: "estimation" },
            { sv: "sent", fr: "tard" },
            { sv: "ett väder", fr: "temps, météo" },
            { sv: "se ut", fr: "avoir l’air" },
            { sv: "ledsen", fr: "triste" },
            { sv: "hålla", fr: "tenir, garder" },
            { sv: "köa (1)", fr: "faire la queue" },
            { sv: "en fåtölj", fr: "fauteuil" },
            { sv: "vänta i regnet", fr: "attendre sous la pluie" },
            { sv: "rekommendera", fr: "recommander" },
            { sv: "en krydda", fr: "épice" },
            { sv: "en staty", fr: "statue" },
            { sv: "ett slott", fr: "château" },
            { sv: "turister", fr: "touristes" },
            { sv: "odla (1)", fr: "cultiver" },
            { sv: "annars", fr: "sinon, autrement" },
            { sv: "förrgår", fr: "avant-hier" },
            { sv: "är duktig att", fr: "être doué en" },
            { sv: "ett möte", fr: "réunion" },
            { sv: "ringa på dörren", fr: "sonner à la porte" },
            { sv: "ett huvud", fr: "chef" },
            { sv: "dejta på nätet", fr: "faire des rencontres en ligne" },
            { sv: "bjuda", fr: "inviter, offrir" },
            { sv: "passa (1)", fr: "convenir" },
            { sv: "låna (1)", fr: "emprunter" },
            { sv: "lämna tillbaka", fr: "rendre" },
            { sv: "långt", fr: "loin" },
            { sv: "länge", fr: "longtemps" },
            { sv: "hur långt?", fr: "quelle distance ?" },
            { sv: "hur länge?", fr: "depuis combien de temps ?" },
            { sv: "stilig", fr: "stylé, élégant" },
            { sv: "en massa", fr: "beaucoup" },
            { sv: "ett bröllop", fr: "mariage" },
            { sv: "tåget är försenat/inställt", fr: "le train est en retard/annulé" },
            { sv: "slumpen bestämmer", fr: "le destin décide" },
            { sv: "desperat", fr: "désespéré" },
            { sv: "en matlagningskurs", fr: "cours de cuisine" },
            { sv: "fuska (1)", fr: "tricher" },
            { sv: "frisk", fr: "en bonne santé" },
            { sv: "lugn", fr: "calme" },
            { sv: "en sömn", fr: "sommeil" },
            { sv: "släppa (2)", fr: "lâcher" },
            { sv: "för länge sedan", fr: "il y a longtemps" },
            { sv: "svara mig", fr: "réponds-moi" },
            { sv: "jag bara undrar", fr: "je me demande juste" },
            { sv: "försvinna", fr: "disparaître" },
            { sv: "igen", fr: "de nouveau, encore" },
            { sv: "ett krig", fr: "guerre" },
            { sv: "hemlagat", fr: "fait maison" },
            { sv: "en korg", fr: "panier" },
            { sv: "en vagn", fr: "chariot" },
            { sv: "ägg", fr: "œufs" },
            { sv: "en nöt", fr: "noix" },
            { sv: "en kassa", fr: "caisse" },
            { sv: "betala kontant", fr: "payer en cash" },
            { sv: "koka (1)", fr: "cuire à l’eau" },
            { sv: "steka (2)", fr: "cuire à la poêle" },
            { sv: "baka (1)", fr: "cuire au four" },
            { sv: "en dill", fr: "aneth" },
            { sv: "ett skal", fr: "carapace" },
            { sv: "en havre", fr: "avoine" },
            { sv: "ett vete", fr: "blé" },
            { sv: "vispa (1)", fr: "fouetter" },
            { sv: "blåbär", fr: "myrtilles" },
            { sv: "hjortron", fr: "mûres des marais" },
            { sv: "björnbär", fr: "mûres" },
            { sv: "hallon", fr: "framboises" },
            { sv: "en tårta", fr: "gâteau" },
            { sv: "en glass", fr: "glace" },
            { sv: "pannkakor", fr: "crêpes" },
            { sv: "inte heller", fr: "pas non plus" },
            { sv: "inte alls", fr: "pas du tout" },
            { sv: "allergisk mot", fr: "allergique à" },
            { sv: "en sparris", fr: "asperge" },
            { sv: "nöttunga", fr: "langue de bœuf" },
            { sv: "gissa (1)", fr: "deviner" },
            { sv: "en bio", fr: "cinéma" },
            { sv: "ett knytis", fr: "repas" },
            { sv: "skrika", fr: "crier" },
            { sv: "väldig", fr: "très, énorme" },
            { sv: "rita (1)", fr: "dessiner" },
            { sv: "nöjd med", fr: "content de" },
            { sv: "tom", fr: "vide" },
            { sv: "en skriva", fr: "tranche" },
            { sv: "är på semester", fr: "être en vacances" },
            { sv: "snusa (1)", fr: "consommer du tabac" },
            { sv: "hälla (2)", fr: "verser" },
            { sv: "hälsa på", fr: "rendre visite" },
            { sv: "bakom", fr: "derrière" },
            { sv: "finns det?", fr: "y a-t-il ?" },
            { sv: "den här", fr: "ceci" },
            { sv: "klara ett prov", fr: "réussir l’examen" },
            { sv: "stänga", fr: "fermer" }
        ],
        "Autre": [
            { sv: "blanda (1)", fr: "mélanger" },
            { sv: "kolsyrat vatten", fr: "eau pétillante" },
            { sv: "krama (1)", fr: "faire une accolade" },
            { sv: "en kram", fr: "accolade" },
            { sv: "en kyss", fr: "bise" },
            { sv: "i stället för", fr: "à la place de" },
            { sv: "ett ljus", fr: "lumière" },
            { sv: "jag antar att", fr: "je suppose que" },
            { sv: "Jo", fr: "si (réponse positive à question négative)" },
            { sv: "ett hjul", fr: "roue" },
            { sv: "en häxa", fr: "sorcière" },
            { sv: "kikärter", fr: "pois chiches" },
            { sv: "bland annat", fr: "entre autres" },
            { sv: "en tång", fr: "algue" },
            { sv: "valla (1)", fr: "guider" },
            { sv: "en fart", fr: "vitesse" },
            { sv: "ett mål", fr: "but" },
            { sv: "första ögonkastet", fr: "au premier regard" },
            { sv: "i början", fr: "au début" },
            { sv: "varandra", fr: "l’un l’autre" },
            { sv: "färdig", fr: "prêt, fini" },
            { sv: "en saga", fr: "conte" },
            { sv: "mittre", fr: "milieu" },
            { sv: "mittemot", fr: "en face de" },
            { sv: "knapp", fr: "à peine" },
            { sv: "byta jobb", fr: "changer de travail" }
        ]
    },
    niveau3: {
        "Livre de cours - Kapitel 17": [
            { sv: "en bostad (städer)", fr: "logement, habitation" },
            { sv: "en villa", fr: "maison" },
            { sv: "en förort (er)", fr: "banlieue" },
            { sv: "strax utanför", fr: "juste à côté" },
            { sv: "en bostadsrätt (er)", fr: "logement en copropriété" },
            { sv: "en hyreslägenhet (er)", fr: "appartement loué" },
            { sv: "hyr (3)", fr: "louer (locataire)" },
            { sv: "hyr ut", fr: "louer (propriétaire)" },
            { sv: "en tvättstuga", fr: "buanderie" },
            { sv: "en öppen spis (ar)", fr: "feu ouvert" },
            { sv: "elda (1)", fr: "faire du feu" },
            { sv: "inomhus", fr: "à l'intérieur" },
            { sv: "i bra skick", fr: "en bon état" },
            { sv: "en tomt (er)", fr: "jardin, cour, terrain" },
            { sv: "sambo", fr: "concubin" },
            { sv: "mambo", fr: "tanguy" },
            { sv: "är särbo", fr: "être en couple sans habiter ensemble" },
            { sv: "hyra en lägenhet i andra hand", fr: "sous-louer un appartement" },
            { sv: "månadsavgift", fr: "cotisation mensuelle" },
            { sv: "ett renoveringsobjekt", fr: "à rénover" },
            { sv: "en balkong (er)", fr: "balcon" },
            { sv: "kakelugn", fr: "poêle en faïence" },
            { sv: "vanligtvis", fr: "habituellement" },
            { sv: "en kokvrå", fr: "coin cuisine" },
            { sv: "en toalett (er)", fr: "toilette" },
            { sv: "vissa", fr: "certains, quelque" },
            { sv: "ett förråd", fr: "débarras" },
            { sv: "en vind (ar)", fr: "grenier (vent)" },
            { sv: "en källare", fr: "cave" },
            { sv: "gemensam", fr: "commun" },
            { sv: "ett radhus", fr: "maison de rangée" },
            { sv: "ett parhus", fr: "maison mitoyenne" },
            { sv: "hemma i mitt hus", fr: "à ma maison" },
            { sv: "ett studentrum", fr: "chambre étudiant" },
            { sv: "en andrahandslägenhet", fr: "appartement sous-loué" },
            { sv: "i närförort", fr: "près des banlieues" },
            { sv: "på pendlingsavstånd", fr: "à une bonne distance pour faire la navette" },
            { sv: "i kollektiv", fr: "en collocation" },
            { sv: "inneboende", fr: "chez l'habitant" },
            { sv: "äntligen", fr: "enfin, finalement" },
            { sv: "kolla (1)", fr: "regarder, vérifier" },
            { sv: "en sajt, er", fr: "site" },
            { sv: "ett sovrum, /", fr: "chambre" },
            { sv: "en trädgård, ar", fr: "jardin" },
            { sv: "högstbjudande", fr: "plus offrant" },
            { sv: "en uppvärmning", fr: "chauffage" },
            { sv: "en sophämtning, ar", fr: "ramassage des poubelles" },
            { sv: "lugn", fr: "calme" },
            { sv: "opraktisk", fr: "pas pratique" },
            { sv: "skön", fr: "confortable" },
            { sv: "städa (1)", fr: "ranger, nettoyer" },
            { sv: "tvätta (1)", fr: "laver, faire la lessive" },
            { sv: "dessutom", fr: "en outre, en plus, d'ailleurs" },
            { sv: "en fördel, ar", fr: "avantage" },
            { sv: "en nackdel, ar", fr: "désavantage" },
            { sv: "Jag tycker att det är bättre att … därför att …", fr: "Je pense que c’est mieux de … parce que …" },
            { sv: "Ja, kanske, men…", fr: "Oui peut-être, mais…" },
            { sv: "jag, det är sant, men", fr: "Oui c’est vrai mais…" },
            { sv: "Ja, det har du rätt i, men", fr: "Oui tu as raison, mais…" },
            { sv: "Nja, jag håller inter riktigt med…", fr: "Moui, je ne suis pas vraiment d’accord…" },
            { sv: "är på väg till", fr: "être sur le chemin de" },
            { sv: "en visning, ar", fr: "visite" },
            { sv: "en mäklare, /", fr: "agent immobilier" },
            { sv: "hälsa (1)", fr: "saluer, accueillir" },
            { sv: "sympatisk", fr: "sympathique" },
            { sv: "ställa (2)", fr: "poser, mettre, placer" },
            { sv: "ställa några frågor", fr: "poser des questions" },
            { sv: "en förening, ar", fr: "association, club, union" },
            { sv: "bläddra (1)", fr: "feuilleter" },
            { sv: "en säljare, /", fr: "vendeur" },
            { sv: "en kristallkrona, or", fr: "lustre" },
            { sv: "svartvita fotografier", fr: "photos en noir et blanc" },
            { sv: "färgglad", fr: "multicolore, bigarré" },
            { sv: "en fil, ar", fr: "couverture" },
            { sv: "en kudde, ar", fr: "oreiller" },
            { sv: "bakom >< framför", fr: "derrière >< devant" },
            { sv: "flytta (1)", fr: "déménager" },
            { sv: "fräsch", fr: "nouveau" },
            { sv: "ett bud", fr: "offre" },
            { sv: "lägga ett bud", fr: "faire une offre" },
            { sv: "mittemot", fr: "en face" },
            { sv: "ovanför", fr: "dessus, au-dessus" },
            { sv: "bredvid", fr: "à côté de" },
            { sv: "mellan…och", fr: "entre…et" },
            { sv: "till höger om", fr: "à droite de" },
            { sv: "till vänster om", fr: "à gauche de" },
            { sv: "under", fr: "sous" },
            { sv: "på", fr: "sur" },
            { sv: "i", fr: "dans" },
            { sv: "i hörnet", fr: "dans le coin" },
            { sv: "i taket", fr: "au plafond" },
            { sv: "ett kylskåp, /", fr: "réfrigérateur" },
            { sv: "ett vykort, /", fr: "carte postale" },
            { sv: "en tidtabell, er", fr: "horaire" },
            { sv: "en vägg, ar", fr: "mur" },
            { sv: "ett matbord, /", fr: "table à manger" },
            { sv: "ett golv, /", fr: "sol" },
            { sv: "en skrivbordslampa, or", fr: "lampe de bureau" },
            { sv: "en matta, or", fr: "tapis" },
            { sv: "ett skåp, /", fr: "armoire, placard" },
            { sv: "en taklampa", fr: "plafonnier, lampe de plafond" },
            { sv: "ett soffbord, /", fr: "table basse" },
            { sv: "ett skrivbord, /", fr: "bureau" },
            { sv: "en bokhylla, or", fr: "bibliothèque" },
            { sv: "en golvlampa, or", fr: "lampe sur pied" },
            { sv: "en gardin, er", fr: "rideau" },
            { sv: "en soffa, or", fr: "canapé, sofa" },
            { sv: "en fåtölj, er", fr: "fauteuil" },
            { sv: "en tavla, or", fr: "tableau" },
            { sv: "en stol, ar", fr: "chaise" },
            { sv: "ett tak, /", fr: "plafond" },
            { sv: "ett fönster, fönstret, fönster, fönstren", fr: "fenêtre" },
            { sv: "en krukväxt, er", fr: "plante d'appartement, plante en pot" },
            { sv: "ett badrum, /", fr: "Salle-de-bain" },
            { sv: "ett kök, /", fr: "cuisine" },
            { sv: "en hall, ar", fr: "couloir" },
            { sv: "en toalett, er", fr: "toilette" },
            { sv: "ett arbetsrum, /", fr: "bureau (pièce)" },
            { sv: "ett vardagsrum, /", fr: "living, salle de séjour" }
        ],
        "Livre de cours - Kapitel 18": [
            { sv: "en apparat, er", fr: "appareil" },
            { sv: "kratta (1) löv", fr: "ratisser les feuilles" },
            { sv: "ha riktigt trevligt", fr: "passer un très bon moment" },
            { sv: "förresten, apropå", fr: "au fait, à propos, soit dit en passant" },
            { sv: "då var det dags", fr: "il faut y aller" },
            { sv: "så funkar det", fr: "c’est comme ça que ça marche" },
            { sv: "sätta på (sätter, satte, satt)", fr: "allumer" },
            { sv: "stänga av (2)", fr: "éteindre" },
            { sv: "sur", fr: "fâché, contrarié" },
            { sv: "en kanna, or", fr: "cruche, pot" },
            { sv: "hälla (2)", fr: "verser, couler" },
            { sv: "en skopa, or", fr: "dosette" },
            { sv: "koppla (1)", fr: "brancher" },
            { sv: "en vaktmästare", fr: "concierge" },
            { sv: "med fjärrkontrollen", fr: "télécommandé" },
            { sv: "vänta en stund", fr: "attendre un moment" },
            { sv: "Tryck (2) in en kod", fr: "introduire un code" },
            { sv: "en knapp, ar", fr: "bouton" },
            { sv: "dubbelsidigt", fr: "recto verso" },
            { sv: "Gör inte själv", fr: "ne faites rien seul" },
            { sv: "Komma först", fr: "arriver en premier" },
            { sv: "är sist", fr: "être dernier" },
            { sv: "Trycka fel kod", fr: "introduire le mauvais code" },
            { sv: "ett larm, /", fr: "alarme" },
            { sv: "ett samtal", fr: "conversation, discussion" },
            { sv: "Slå in ett nummer", fr: "taper un numéro" },
            { sv: "en klippning, er", fr: "coupe" },
            { sv: "sucka (1)", fr: "souffler" },
            { sv: "förlora (1)", fr: "perdre" },
            { sv: "ett lånekort, /", fr: "carte de bibliothèque" },
            { sv: "stort tack för hjälpen", fr: "un grand merci pour votre aide" },
            { sv: "få kontakt med", fr: "entrer en contact avec" },
            { sv: "ingå (ingår, ingick, ingått)", fr: "comprendre, faire partie de" },
            { sv: "hända (händer, hände, hänt)", fr: "se produire, se passer" },
            { sv: "ge upp (ger, gav, gett)", fr: "abandonner" },
            { sv: "tjäna (1) pengar", fr: "gagner de l’argent" },
            { sv: "lugna (1)", fr: "calmer" },
            { sv: "gråta (2)", fr: "pleurer" }
        ],
        "Livre de cours - Kapitel 1": [
            { sv: "en idrott, er", fr: "Sport" },
            { sv: "En skärm, ar", fr: "Écran" },
            { sv: "Slappa (1)", fr: "Se détendre" }
        ],
        "Livre de cours - Kapitel 3": [
            { sv: "Fira jul", fr: "Fêter Noël" },
            { sv: "Sluta jobba", fr: "Arrêter de travailler" },
            { sv: "Oberoende", fr: "Indépendant" },
            { sv: "Ett friskt och långt liv", fr: "Une vie en bonne santé et longue" },
            { sv: "Det perfekta jobbet", fr: "Ekonomisk frihet" },
            { sv: "Balans i livet", fr: "Équilibre dans la vie" },
            { sv: "En kärlek", fr: "Amour" },
            { sv: "Träffa en idol", fr: "Rencontrer son idole" },
            { sv: "Resa till rymden", fr: "Faire le tour du monde" },
            { sv: "Vara vacker hela livet", fr: "Être beau toute ma vie" },
            { sv: "Modig", fr: "Courageux, brave" },
            { sv: "Smart", fr: "Intelligent" },
            { sv: "Bra på matte", fr: "Bon en math" },
            { sv: "Oärlig", fr: "malhonnête" },
            { sv: "Arbetsam", fr: "Travailleur, assidu" },
            { sv: "Fräck", fr: "Impudent, impertinent, insolent" },
            { sv: "galen (galet, galna)", fr: "fou" },
            { sv: "lida (lider, led, lidit)", fr: "souffrir" },
            { sv: "vara tvungen / måste", fr: "obliger" },
            { sv: "odla (1)", fr: "cultiver" },
            { sv: "slippa (slipper, slapp, sluppit)", fr: "ne pas devoir, échapper à" },
            { sv: "vana (-n, -or)", fr: "habitude" },
            { sv: "beroende / oberoende", fr: "dépendant / indépendant" },
            { sv: "när det gäller…", fr: "en ce qui concerne…" },
            { sv: "funka (1)", fr: "fonctionner" },
            { sv: "höna (-n, -or)", fr: "Poule" },
            { sv: "Ett lån, /", fr: "Prêt, emprunt" },
            { sv: "I slutet på året", fr: "À la fin de l’année" },
            { sv: "Deltid", fr: "Temps partiel" },
            { sv: "Jag jobbar 30 timmar i veckan", fr: "Je travaille 30 h/semaine" },
            { sv: "Slipper resorna", fr: "Échapper aux trajets" },
            { sv: "En vana, or", fr: "Habitude" },
            { sv: "En investering", fr: "Investissement" },
            { sv: "Prioritera (1)", fr: "Favoriser, prioriser" },
            { sv: "Ett skafferi, er", fr: "Garde-manger, cellier" },
            { sv: "Solnedgången över havet", fr: "Coucher de soleil sur la mer" },
            { sv: "I vardagen i småsaker", fr: "Les petites choses de la vie quotidienne" },
            { sv: "Plocka (1) ägg", fr: "Ramasser les œufs" },
            { sv: "Semetrar", fr: "Passer des vacances" },
            { sv: "I tält", fr: "En tente" }
        ],
        "Livre de cours - Kapitel 4": [
            { sv: "avsnitt (-et, /)", fr: "paragraphe" },
            { sv: "i nödsituation", fr: "en cas d’urgence" },
            { sv: "vapen (vapnet, /)", fr: "arme" },
            { sv: "ett lår", fr: "une cuisse" },
            { sv: "en groda", fr: "une grenouille" },
            { sv: "låtsas (1)", fr: "faire semblant" },
            { sv: "ett grodlår", fr: "une cuisse de grenouille" },
            { sv: "en skilsmässa", fr: "un divorce" },
            { sv: "köra (2) upp", fr: "passer le permis de conduire" },
            { sv: "en svan (-ar)", fr: "un cygne" },
            { sv: "en varg (-ar)", fr: "un loup" },
            { sv: "en älg (-ar)", fr: "un élan" },
            { sv: "en katt (-er)", fr: "un chat" },
            { sv: "en orm (-ar)", fr: "un serpent" },
            { sv: "en fisk (-ar)", fr: "un poisson" },
            { sv: "en hund (-ar)", fr: "un chien" },
            { sv: "en gris (-ar)", fr: "un cochon" },
            { sv: "en kanin, er", fr: "lapin" },
            { sv: "en hund, ar", fr: "chien" },
            { sv: "en häst, ar", fr: "cheval" },
            { sv: "en geting, ar", fr: "guêpe" },
            { sv: "en björn, ar", fr: "ours" },
            { sv: "en fågel, fåglar", fr: "oiseau" },
            { sv: "en råtta, or", fr: "rat, souris" },
            { sv: "en fästing, ar", fr: "tique" },
            { sv: "Självständig", fr: "indépendant" },
            { sv: "trofast", fr: "fidèle" },
            { sv: "tyst", fr: "silencieux" },
            { sv: "lydig", fr: "obéissant" },
            { sv: "busig", fr: "turbulent" },
            { sv: "stilig", fr: "élégant" },
            { sv: "lugn", fr: "calme" },
            { sv: "vacker", fr: "beau" },
            { sv: "gullig", fr: "mignon" },
            { sv: "intelligent", fr: "intelligent" },
            { sv: "stark", fr: "fort" },
            { sv: "lekfull", fr: "jouette, joueur, espiègle" },
            { sv: "pålitlig", fr: "fiable" },
            { sv: "opålitlig", fr: "pas digne de confiance" },
            { sv: "graciös", fr: "gracieux" },
            { sv: "påhittig", fr: "imaginatif" },
            { sv: "klumpig", fr: "maladroit" },
            { sv: "ilsken", fr: "fâché, colérique" },
            { sv: "korkad, de", fr: "stupide" },
            { sv: "farlig", fr: "dangereux" },
            { sv: "sällskaplig", fr: "Sociable" },
            { sv: "Hungrig som en varg", fr: "une faim de loup" },
            { sv: "Snabb som en vessla", fr: "rapide comme une belette" },
            { sv: "Tyst som en mus", fr: "discret comme une souris" },
            { sv: "Hal som en ål", fr: "glissant comme une anguille" },
            { sv: "Flitig som en myra", fr: "travailleur comme une fourmi" },
            { sv: "Envis som en åsna", fr: "têtu comme une mule" },
            { sv: "Arg som ett bi", fr: "en colère comme une abeille" },
            { sv: "Att äta som en häst", fr: "manger comme un cheval" },
            { sv: "Stark som en oxe", fr: "fort comme un boeuf" }
        ],
        "Livre de cours - Kapitel 4 (s.50-51)": [
            { sv: "Ha huvudvärk", fr: "avoir mal de tête" },
            { sv: "ett luktsinne", fr: "un sens de l’odorat" },
            { sv: "Ett ljud", fr: "Bruit, son" },
            { sv: "ett påstående", fr: "une affirmation" },
            { sv: "en huggorm", fr: "une vipère" },
            { sv: "ett bett", fr: "une morsure" },
            { sv: "vara rädd för", fr: "avoir peur de" },
            { sv: "ett stick", fr: "une piqure" },
            { sv: "en sjukdom (-ar)", fr: "une maladie" },
            { sv: "nämligen", fr: "en effet" },
            { sv: "dock", fr: "cependant" },
            { sv: "det svider", fr: "ça brûle" },
            { sv: "det gör ont", fr: "ça fait mal" },
            { sv: "svullna (1) (upp)", fr: "gonfler" },
            { sv: "bita – biter, bet, bitit -> biten, bitet, bitna", fr: "mordre" },
            { sv: "en (blod)åder eller ådra", fr: "un vaisseau sanguin" },
            { sv: "vart åttonde år", fr: "tous les huit ans" },
            { sv: "ändå", fr: "Cependant, néanmoins" },
            { sv: "våga (1)", fr: "oser" },
            { sv: "Orsaka (1)", fr: "Causer" },
            { sv: "Livsfarlig", fr: "Mortel" },
            { sv: "En mun, ar", fr: "Bouche" },
            { sv: "en tunga", fr: "une langue" },
            { sv: "andas (1)", fr: "respirer" },
            { sv: "ett lidande", fr: "une souffrance" },
            { sv: "överföra (2)", fr: "transmettre" },
            { sv: "en behandling (-ar)", fr: "un traitement" },
            { sv: "på grund av", fr: "à cause de (=pga)" },
            { sv: "En värk, ar", fr: "Douleur" },
            { sv: "en led", fr: "un membre (du corps)" },
            { sv: "Överföra", fr: "Transférer, communiquer" },
            { sv: "ett ansikte", fr: "un visage" },
            { sv: "en förlamning (-ar)", fr: "une paralysie" },
            { sv: "smitta (1)", fr: "contaminer" }
        ],
        "Livre de cours - Kapitel 4 (s.52-54 Två vilda djur)": [
            { sv: "Vild", fr: "Sauvage" },
            { sv: "Ett ben, /", fr: "Jambe, patte" },
            { sv: "Bakbenen", fr: "Pattes arrières" },
            { sv: "Lufsa (1)", fr: "Marcher d’un pas lourd" },
            { sv: "känna (2)", fr: "sentir" },
            { sv: "en lukt (-er)", fr: "odeur" },
            { sv: "fredlig", fr: "paisible, pacifique" },
            { sv: "Skada (1)", fr: "Endommager" },
            { sv: "ett skott, /", fr: "tir" },
            { sv: "en hona (-or) - en hanne (-ar)", fr: "une femelle, un mâle" },
            { sv: "Överraska (1)", fr: "Surprendre, étonner" },
            { sv: "Sammanlagt", fr: "En tout, au total" },
            { sv: "Ett sår", fr: "Blessure" },
            { sv: "jämföra (2)", fr: "comparer (med)" },
            { sv: "en jämförelse (-r)", fr: "une comparaison" },
            { sv: "Krocka (1)", fr: "Heurter, entrer en collision" },
            { sv: "Hosta (1)", fr: "Tousser" },
            { sv: "Harkla (1)", fr: "Se racler la gorge" },
            { sv: "skicklig", fr: "Adroit, habile, capable" },
            { sv: "En saga, or", fr: "Conte, histoire" },
            { sv: "våld (-et)", fr: "violence" },
            { sv: "elak", fr: "méchant" },
            { sv: "blodtörstig", fr: "assoifé de sang" },
            { sv: "En släkt, er", fr: "famille" },
            { sv: "ske (3) = hända (2)", fr: "se passer" },
            { sv: "stamfader", fr: "ancêtre" },
            { sv: "givetvis", fr: "évidemment" },
            { sv: "Ett sällskap, ett", fr: "Compagnie" },
            { sv: "ramla (1)", fr: "tomber" },
            { sv: "Bryt (2)", fr: "Briser, casser" },
            { sv: "Likna (1)", fr: "Comparer, ressembler" },
            { sv: "hålla i fångenskap", fr: "tenir en captivité" },
            { sv: "släppa (2)", fr: "laisser sortir, laisser tomber, lâcher" },
            { sv: "en korsning (-ar)", fr: "un croisement" },
            { sv: "angripa (angrep, angripit)", fr: "attaquer" },
            { sv: "anfalla (anföll, anfallit)", fr: "attaquer" },
            { sv: "vända (2) sig om", fr: "se retourner" },
            { sv: "vifta (1)", fr: "agiter" },
            { sv: "sparka (1)", fr: "donner des coups de pied" },
            { sv: "springa (sprang, sprungit)", fr: "courir" },
            { sv: "mankhöjd", fr: "hauteur du garrot" },
            { sv: "en valp (-ar)", fr: "un chiot" },
            { sv: "en grävling (-ar)", fr: "un blaireau" },
            { sv: "ett får", fr: "un mouton" },
            { sv: "även", fr: "aussi, même" }
        ],
        "Livre de cours - Kapitel 4 (p.57)": [
            { sv: "Berusad", fr: "Ivre, saoul" },
            { sv: "Skrämma (2)", fr: "Effrayer" },
            { sv: "Halvsovande", fr: "À moitié endormi" },
            { sv: "Hindra", fr: "Empêcher, gêner" },
            { sv: "Sakta (1)", fr: "Ralentir" },
            { sv: "Iväg", fr: "Vite / au loin" },
            { sv: "Dräktig", fr: "Enceinte (animaux)" },
            { sv: "Föredra (1)", fr: "Préférer" },
            { sv: "Vila (1)", fr: "Reposer" },
            { sv: "Under uppsikt", fr: "Sous surveillance" },
            { sv: "Isig", fr: "Verglacé" },
            { sv: "Därmed", fr: "Donc" }
        ],
        "Livre de cours - Kapitel 5": [
            { sv: "Koppla av (1)", fr: "Décontracter, se détendre" },
            { sv: "Förr i tiden", fr: "Autrefois" },
            { sv: "Lättlagad mat", fr: "Nourriture facile à préparer" },
            { sv: "Plockmat", fr: "À picorer" },
            { sv: "Hemgjord", fr: "Fait maison" },
            { sv: "Hämtmat", fr: "Take-away" },
            { sv: "Mysa (2)", fr: "Sourire / Passer un moment agréable" },
            { sv: "Skapa (1)", fr: "Créer, construire" },
            { sv: "Onyttig mat", fr: "Malbouffe" },
            { sv: "Bidra (1)", fr: "Contribuer" },
            { sv: "En övervikt", fr: "Surpoids" },
            { sv: "Ett säljargument", fr: "Argument de vente" },
            { sv: "En koppling", fr: "Connexion" },
            { sv: "Mjukiskläder", fr: "Vêtements mous" },
            { sv: "Träningskläder", fr: "Tenue de sport" },
            { sv: "Morgonrock", fr: "Robe de chambre" }
        ],
        "Livre de cours - Kapitel 5 (p.62)": [
            { sv: "Kom igen", fr: "Allez! (pour motiver)" },
            { sv: "Snälla", fr: "STP" },
            { sv: "Jag helt pank", fr: "Je suis fauché" },
            { sv: "En liten stund", fr: "Un petit moment" }
        ],
        "Livre de cours - Kapitel 5 (Bilar, löständer och annat)": [
            { sv: "ingen annanstans", fr: "nulle part ailleurs" },
            { sv: "aktiebolag = ab", fr: "société anonyme" },
            { sv: "tom", fr: "vide" },
            { sv: "löständer", fr: "dentier" },
            { sv: "sur", fr: "acide" },
            { sv: "seg", fr: "résistant, qu’on peut étendre" },
            { sv: "en kedja, or", fr: "une chaîne" },
            { sv: "skorpor", fr: "biscottes / crisprolls" },
            { sv: "ett hot, /", fr: "une menace" },
            { sv: "En hälsa", fr: "la santé" },
            { sv: "En burk", fr: "un bocal" },
            { sv: "En kiosk, er", fr: "Kiosque, magasin" },
            { sv: "Peka (1)", fr: "indiquer, montrer" },
            { sv: "Plockgodis", fr: "en vrac" },
            { sv: "Lösviktsgodis", fr: "Bonbons en vrac" },
            { sv: "Succé, n", fr: "Succès, réussite" },
            { sv: "Nuförtiden", fr: "Actuellement, de nos jours" },
            { sv: "En mängd, er", fr: "quantité" },
            { sv: "En tom påse", fr: "un sachet vide" },
            { sv: "Välkänd", fr: "Connu, bien connu" },
            { sv: "Matvarukedja", fr: "chaine de magasin alimentaire" },
            { sv: "Oväntade saker", fr: "produits inattendus" },
            { sv: "Ärter", fr: "petits pois" },
            { sv: "Frysta tårtor", fr: "gâteau à la crème surgelé" },
            { sv: "Varor", fr: "Denrée, marchandise" },
            { sv: "Skorpa", fr: "biscotte" },
            { sv: "Pepparkakor", fr: "pain d’épice" },
            { sv: "Ett mål", fr: "but" },
            { sv: "Biter på naglarna", fr: "ronger ses ongles" },
            { sv: "Svär mycket", fr: "jurer beaucoup" },
            { sv: "Petar sig i näsan", fr: "se curer le nez" },
            { sv: "Smaskar när man äter", fr: "faire du bruit en mangeant" },
            { sv: "Beroende", fr: "dépendance, dépendant" },
            { sv: "Sugen på", fr: "Avoir envie de qqc sur le moment" },
            { sv: "Missbrukar", fr: "abuser de" }
        ],
        "Livre de cours - Kapitel 5 (Från kåda till Aladdin 70)": [
            { sv: "Tugga (1)", fr: "Mâcher, chiquer" },
            { sv: "En kåda, or", fr: "résine" },
            { sv: "En honung", fr: "Miel" },
            { sv: "En björk, ar", fr: "Bouleau (arbre)" },
            { sv: "Söt", fr: "sucré, mignon" },
            { sv: "Tillverka(1)", fr: "fabriquer" },
            { sv: "en tillverkning (-ar)", fr: "fabrication" },
            { sv: "så småningom", fr: "peu à peu" },
            { sv: "Ett socker", fr: "sucre" },
            { sv: "Först", fr: "seulement, qu’au (de manière temporelle)" },
            { sv: "Handeln", fr: "faire du commerce" },
            { sv: "På 1500-talet", fr: "au 16ème siècle" },
            { sv: "Konfekt", fr: "confiserie" },
            { sv: "En skillnad, er", fr: "différence" },
            { sv: "På den tiden", fr: "à cette époque" },
            { sv: "Sötsaker", fr: "sucreries" },
            { sv: "En kropp, ar", fr: "corps" },
            { sv: "Godisgris, ar", fr: "Amateur de choses sucrées" },
            { sv: "Emellertid", fr: "Cependant" },
            { sv: "Återvända (2)", fr: "rentrer, retourner" },
            { sv: "En sockerbagare", fr: "un patissier" },
            { sv: "Anställde", fr: "engager" },
            { sv: "Konstnärer", fr: "un artiste" },
            { sv: "Mer eller mindre", fr: "plus ou moins" },
            { sv: "Till och med (tom)", fr: "jusqu’à ce que, même, y compris" },
            { sv: "En mandel, ar", fr: "amende" },
            { sv: "Sockerbeta", fr: "betteraves sucrières" },
            { sv: "Syrener", fr: "lilas" },
            { sv: "Rosenblad", fr: "pétale de rose" },
            { sv: "brända mandlar", fr: "amandes grillées" },
            { sv: "Mot slutet av 1800", fr: "vers la fin du 19ème" },
            { sv: "En lycka, or", fr: "Bonheur, chance" },
            { sv: "tack vare", fr: "grâce à" },
            { sv: "masstillverkning", fr: "fabrication de masse" },
            { sv: "odling", fr: "culture" },
            { sv: "syssla med (1)", fr: "être occupé à" },
            { sv: "ett torg", fr: "marché" },
            { sv: "en änka, or", fr: "veuve" },
            { sv: "polkagrisar", fr: "sucre d'orge" },
            { sv: "förmögen", fr: "Riche, fortuné" },
            { sv: "källarfabrik", fr: "entreprise en sous-sol" },
            { sv: "Till en början", fr: "au début" },
            { sv: "En gatuförsäljare", fr: "marchands ambulants" },
            { sv: "En gumma, or", fr: "une vieille femme" },
            { sv: "En gubbe, ar", fr: "Bonhomme, vieil homme" },
            { sv: "En strut, ar", fr: "Cornet" },
            { sv: "En kola", fr: "caramel" },
            { sv: "En ask", fr: "petite boite" },
            { sv: "ett genombrott (/)", fr: "une percée" },
            { sv: "en tablettask (-ar)", fr: "boîte de pastilles" },
            { sv: "En försäljning, ar", fr: "vente" },
            { sv: "På så sett", fr: "de cette façon" },
            { sv: "Få tag på godis", fr: "se procurer des bonbons" },
            { sv: "Järnvägsstation", fr: "gare" },
            { sv: "Får godis i tänderna", fr: "avoir une carie" },
            { sv: "Har råd att", fr: "avoir les moyens de" }
        ],
        "Livre de cours - Kapitel 6": [
            { sv: "Om du var kung eller drottning för en dag…", fr: "Si tu étais roi au reine..." },
            { sv: "bjuda (bjöd, bjudit)", fr: "offrir, inviter" },
            { sv: "en polare, /arna", fr: "un pote" },
            { sv: "en häst (-ar)", fr: "un cheval" },
            { sv: "Ta det lugnt", fr: "Se la couler douce" },
            { sv: "Himla kul", fr: "Génial, très fun" },
            { sv: "Chilla (1)", fr: "Se détendre" },
            { sv: "osynlig", fr: "invisible" },
            { sv: "semester", fr: "vacances" },
            { sv: "surströmming", fr: "hareng fermenté" },
            { sv: "en måne (månar)", fr: "une lune" },
            { sv: "Resa till månen", fr: "Aller sur la lune" }
        ],
        "Livre de cours - Kapitel 6 (Kungafamiljen)": [
            { sv: "tillhöra (2)", fr: "appartenir à (= höra till)" },
            { sv: "en släkt (-er)", fr: "famille au sens large" },
            { sv: "välja (valde, valt)", fr: "choisir, élire" },
            { sv: "vanlig", fr: "ordinaire" },
            { sv: "be (någon) om lov att…", fr: "demander (à quelqu’un) la permission de…" },
            { sv: "beredd att", fr: "prêt à (=redo att)" },
            { sv: "delta (deltog,deltagit) i", fr: "participer à" },
            { sv: "gå i arv", fr: "être héréditaire" },
            { sv: "ett arv", fr: "un héritage" },
            { sv: "En flagga, or", fr: "drapeau" },
            { sv: "Behålla, behåller, behöll, behållit", fr: "conserver, maintenir" },
            { sv: "Införa, inför", fr: "adopter, introduire, approuver" },
            { sv: "En republik", fr: "république" },
            { sv: "En monarki", fr: "monarchie" },
            { sv: "Ett kejsardöme", fr: "Empire" },
            { sv: "En diktatur", fr: "Dictature" },
            { sv: "Ett parlament", fr: "Parlement" },
            { sv: "En president", fr: "Président" },
            { sv: "En premiärminister", fr: "Premier ministre" },
            { sv: "En statsminister", fr: "Premier ministre (Suède)" },
            { sv: "En kung", fr: "Roi" },
            { sv: "En drottning", fr: "Reine" },
            { sv: "En diktator", fr: "Dictateur" },
            { sv: "En parlamentsledamot", fr: "Membre du parlement" },
            { sv: "enda", fr: "seul (unique)" },
            { sv: "ytterligare", fr: "supplémentaire" },
            { sv: "ett avbrott", fr: "une interruption" },
            { sv: "förändras (1)", fr: "changer, se transformer" },
            { sv: "ett uttryck", fr: "une expression" },
            { sv: "ersätta (ersatte, ersatt)", fr: "remplacer" },
            { sv: "ett samhälle (-n)", fr: "une société" },
            { sv: "en jämlikhet", fr: "égalité" },
            { sv: "samförstånd", fr: "bonne entente, unité" },
            { sv: "välfärdsstaten", fr: "l’etat du bien-être = l’etat providence" },
            { sv: "barnbidrag", fr: "allocations familiales" },
            { sv: "ett bidrag", fr: "une contribution, allocation" },
            { sv: "tilläggspension", fr: "pension complémentaire" },
            { sv: "ett jordbruk", fr: "agriculture" },
            { sv: "en skala", fr: "une échelle" },
            { sv: "en utgift (-er)", fr: "une dépense" },
            { sv: "ett samarbete (-n)", fr: "une collaboration" },
            { sv: "ta (tog, tagit) över", fr: "reprendre" },
            { sv: "Av världens stabilaste", fr: "le plus stable du monde" },
            { sv: "Allmän", fr: "général, commun" },
            { sv: "Finansiera (1)", fr: "financer" },
            { sv: "Ökad export", fr: "Exportation accrue" },
            { sv: "Höga skatter", fr: "Impôts élevés" },
            { sv: "Mena", fr: "signifier, penser" },
            { sv: "Klassamhälle", fr: "Société de classe" },
            { sv: "Progressiv skatteskala", fr: "Barème d'imposition progressif" },
            { sv: "Borgerlig (adj)", fr: "bourgeois" },
            { sv: "Svag", fr: "faible" },
            { sv: "En kärnkraft, er", fr: "énergie nucléaire" },
            { sv: "En åsikt, er", fr: "point de vue" },
            { sv: "Ett syre", fr: "oxygène" },
            { sv: "Ett parti, er", fr: "parti" },
            { sv: "Ett undantag, /", fr: "exception" }
        ],
        "Livre de cours - Kapitel 6 (24/11)": [
            { sv: "Släppa ut", fr: "laisser sortir" },
            { sv: "Förorening", fr: "Pollution" },
            { sv: "Skräp", fr: "déchets" },
            { sv: "Annars", fr: "sinon" },
            { sv: "En kampanj", fr: "Une campagne" },
            { sv: "Informera om", fr: "Informer sur" },
            { sv: "Sätta upp affischer", fr: "Placarder des affiches" }
        ],
        "Livre de cours - Kapitel 6 (30/11)": [
            { sv: "Innehålla", fr: "Contenir" },
            { sv: "Statskick", fr: "Régime politique" },
            { sv: "Friheter", fr: "libertés" },
            { sv: "Rättigheter", fr: "droits" },
            { sv: "Skydda", fr: "Protéger" },
            { sv: "Människans", fr: "Humain" },
            { sv: "En val", fr: "Une élection / Un choix" },
            { sv: "Gå till", fr: "aller à / se dérouler" },
            { sv: "En medborgare", fr: "citoyen" },
            { sv: "Rösta (1)", fr: "élire, voter" },
            { sv: "Omkring", fr: "environ" },
            { sv: "En rösträtt", fr: "droit de vote" },
            { sv: "En röst, er", fr: "voix" },
            { sv: "Vart fjärde år", fr: "tous les 4 ans" },
            { sv: "I rad", fr: "en suivant, de suite" },
            { sv: "Ett förslag", fr: "proposition" },
            { sv: "Myndigheter", fr: "autorités" },
            { sv: "Sköta, sköter, skötte, skött", fr: "gérer, s’occuper de" },
            { sv: "Styr", fr: "Diriger" },
            { sv: "Föreslår", fr: "Proposer" },
            { sv: "Enligt", fr: "selon" },
            { sv: "Det innebär att", fr: "Cela implique que" },
            { sv: "är förbjudet", fr: "être interdit" },
            { sv: "självständigt", fr: "indépendamment" },
            { sv: "i detalj", fr: "en détail" },
            { sv: "ta hand om", fr: "s'occuper de" },
            { sv: "erbjuda", fr: "offrir" }
        ],
        "Livre de cours - Kapitel 6 (01/12)": [
            { sv: "Smultron", fr: "fraises des bois" },
            { sv: "grässtrå", fr: "brin d’herbe" },
            { sv: "trä upp", fr: "enfiler" },
            { sv: "sylt", fr: "confiture" },
            { sv: "saft", fr: "Jus/sirop" },
            { sv: "nyttig", fr: "utile / sain" },
            { sv: "betydelse", fr: "signification" },
            { sv: "hemlig", fr: "secret" }
        ],
        "Livre de cours - Kapitel 6 (07/12 - 96)": [
            { sv: "Husmanskost", fr: "Cuisine traditionnelle" },
            { sv: "Ett samlingsnamn", fr: "nom d’ensemble" },
            { sv: "Kalla (1)", fr: "Appeler" },
            { sv: "Noga med att", fr: "faire attention à" },
            { sv: "En anledning", fr: "Une raison" },
            { sv: "Närproducerad", fr: "produit localement" },
            { sv: "Avriven", fr: "râpé" },
            { sv: "Vetemjöl", fr: "farine de froment" },
            { sv: "Fläsk", fr: "porc, lard" },
            { sv: "Tärnat", fr: "coupé en dés" },
            { sv: "En klick smör", fr: "noisette de beurre" },
            { sv: "Smälta (2)", fr: "fondre" },
            { sv: "Tillbehör", fr: "Accessoire / Accompagnement" },
            { sv: "Övrig", fr: "qui reste, restant, autre" },
            { sv: "Trötthet", fr: "fatigue" },
            { sv: "Ugnsgräddad", fr: "cuit au four" },
            { sv: "Pannkaka", fr: "crêpes" },
            { sv: "Russin", fr: "raisin sec" },
            { sv: "Vispad grädde", fr: "crème fouettée" },
            { sv: "Salmbär", fr: "mûres bleues" },
            { sv: "Skånska", fr: "scanien" },
            { sv: "En gås, /", fr: "oie" },
            { sv: "Består av", fr: "Consiste en" },
            { sv: "Ingefära", fr: "gingembre" }
        ],
        "Autre": [
            { sv: "hälsa som mig", fr: "salutations de ma part" },
            { sv: "tulltjänstemän", fr: "fonctionnaire à la douane" },
            { sv: "muta (1)", fr: "corrompre" },
            { sv: "spå, spår", fr: "prédire, prévoir" },
            { sv: "bryta sig in (bröt, brutit)", fr: "s’introduire par effraction" },
            { sv: "på bar gärning", fr: "en flagrant délit" },
            { sv: "inkomster", fr: "revenus" },
            { sv: "utgifter", fr: "dépenses" },
            { sv: "fly (3)", fr: "fuir" },
            { sv: "svarta hål", fr: "trou noir" },
            { sv: "hjärtinfarkt", fr: "infarctus" },
            { sv: "en spruta, r", fr: "piqure" },
            { sv: "göra slut", fr: "rompre" },
            { sv: "en dragspel", fr: "accordéon" },
            { sv: "en brygga, or", fr: "ponton" },
            { sv: "driver ni med mig?", fr: "Vous vous moquez de moi ?" },
            { sv: "Sakta", fr: "Lentement" },
            { sv: "Bred", fr: "Large" },
            { sv: "Krokig", fr: "Tortueux, pas droit" },
            { sv: "Het", fr: "chaud, brûlant" },
            { sv: "Tjock", fr: "Épais, gros" },
            { sv: "Djup", fr: "Profond, en profondeur" },
            { sv: "Torr", fr: "Sec" },
            { sv: "Sällan", fr: "Rare" },
            { sv: "Inte förgäves", fr: "En vain" },
            { sv: "Fort", fr: "Rapide" },
            { sv: "Stor", fr: "Grand" },
            { sv: "Lång", fr: "Long, grand" },
            { sv: "Trång", fr: "Étroit" },
            { sv: "Rak", fr: "Droit" },
            { sv: "Sval", fr: "Frais" },
            { sv: "tunn", fr: "Mince, maigre" },
            { sv: "Grund", fr: "Peu profond" },
            { sv: "Blöt", fr: "Mouillé" },
            { sv: "Tät", fr: "Dense, serré" },
            { sv: "Lät", fr: "Facile" },
            { sv: "För sent", fr: "Trop tard" },
            { sv: "Någonstans", fr: "Quelque part" },
            { sv: "Trygg", fr: "Sécurisé, réconfortant" },
            { sv: "Ett strykjärn", fr: "Fer à repasser" },
            { sv: "Ett badkar, /", fr: "baignoire" },
            { sv: "Ett handfat", fr: "lavabo" },
            { sv: "En spegel, ar", fr: "miroir" },
            { sv: "En spis, ar", fr: "Feu ouvert / Cuisinière" },
            { sv: "En ugn, ar", fr: "Four" },
            { sv: "En galge, ar", fr: "cintre" },
            { sv: "Otänkbar", fr: "Impensable" },
            { sv: "Underhålla", fr: "Entretenir" },
            { sv: "Snatta (1)", fr: "Voler, piquer" },
            { sv: "Tända (2)", fr: "Allumer (lampe, feu)" },
            { sv: "Släcka (2)", fr: "Éteindre (lampe, feu)" },
            { sv: "Var vanlig", fr: "Veuillez…" },
            { sv: "Knappa in (1)", fr: "encoder" },
            { sv: "Avsluta med (1)", fr: "Terminer avec" },
            { sv: "Ett ärende, en", fr: "Question, sujet, affaire" },
            { sv: "Gälla (2)", fr: "concerner" },
            { sv: "Upprepa (1)", fr: "Répéter" },
            { sv: "Världens", fr: "Du monde" },
            { sv: "Stilla havet", fr: "Océan pacifique" },
            { sv: "Smitta av (1)", fr: "Être contaminé" },
            { sv: "Omsorg", fr: "souci" },
            { sv: "ökning", fr: "Augmentation" },
            { sv: "Inse (inser, insåg, insett)", fr: "Se rendre compte" },
            { sv: "Särskil", fr: "Particulièrement" },
            { sv: "En rymd, er", fr: "Espace, volume" },
            { sv: "Jäklig", fr: "Foutrement, sacrément" },
            { sv: "Olaglig", fr: "Illégal" },
            { sv: "Ett straff, /", fr: "Peine, punition" },
            { sv: "Öka (2)", fr: "Augmenter" },
            { sv: "Försäkringskassa", fr: "Caisse mutuelle" },
            { sv: "En belöning, ar", fr: "Récompense" },
            { sv: "Ett förhör", fr: "Interrogatoire" },
            { sv: "Råna (1)", fr: "Cambrioler, voler, dévaliser" },
            { sv: "Ett fängelse, er", fr: "Prison" },
            { sv: "hemlighålla", fr: "Dissimuler" },
            { sv: "Kräkas, kräks, kräktes, kräkts", fr: "Vomir" },
            { sv: "erkänna", fr: "Reconnaitre, admettre" },
            { sv: "Slarvig", fr: "Négligent, négligé, débraillé" },
            { sv: "Käka (1)", fr: "Manger (bouffer)" },
            { sv: "Skoja (1)", fr: "Plaisanter, blaguer" },
            { sv: "Lova (1)", fr: "Promettre, assurer" },
            { sv: "skyldig", fr: "Coupable" },
            { sv: "Knyta (2)", fr: "Nouer, lier, attacher" },
            { sv: "Natti, natti", fr: "Bonne nuit" },
            { sv: "få sparken", fr: "Se faire virer" },
            { sv: "frisör -> friss", fr: "coiffeur" },
            { sv: "en domstol", fr: "tribunal" },
            { sv: "tingsrätt", fr: "tribunal de première instance" },
            { sv: "en åklagare", fr: "procureur général" },
            { sv: "slipper straff", fr: "ne pas recevoir de peine" },
            { sv: "hinna aldrig tid", fr: "ne pas avoir le temps" },
            { sv: "på toa", fr: "toilettes" },
            { sv: "låna toaletten", fr: "emprunter les toilettes" },
            { sv: "skärp dig", fr: "ressaisi-toi" },
            { sv: "gå ut", fr: "expirer, toucher à sa fin" },
            { sv: "håller helt och hållet med", fr: "je suis entièrement d’accord" },
            { sv: "håller delvis med", fr: "je suis en partie d’accord" },
            { sv: "håller inte alls med", fr: "je ne suis pas du tout d’accord" },
            { sv: "varken … eller", fr: "ni…ni" },
            { sv: "antigen … eller", fr: "soit…soit" },
            { sv: "både … och", fr: "… et … (les deux)" },
            { sv: "högfärdig", fr: "hautain" },
            { sv: "pigg", fr: "en pleine forme" },
            { sv: "större chans", fr: "plus de chance de" },
            { sv: "undervisa", fr: "enseigner" },
            { sv: "det gör inget", fr: "ça ne fait rien, c’est pas grave" },
            { sv: "tack för skjutsen", fr: "merci de m’avoir déposé" },
            { sv: "jävlarna", fr: "enfoirés" },
            { sv: "lura (1)", fr: "tromper, tricher" },
            { sv: "alla hjärtans dag", fr: "Saint-Valentin" },
            { sv: "tacka (1)", fr: "remercier" },
            { sv: "smidig", fr: "souple, flexible" },
            { sv: "hyser mig", fr: "abriter" },
            { sv: "svartsjuk", fr: "jaloux" },
            { sv: "kär i mig", fr: "amoureux de moi" },
            { sv: "låtsas (låtsades, låtsats)", fr: "faire semblant de" },
            { sv: "skada (1)", fr: "blesser" },
            { sv: "hota (1)", fr: "menacer" },
            { sv: "misstänka (2)", fr: "soupçonner" },
            { sv: "område", fr: "environs, secteur" },
            { sv: "obebodd", fr: "inhabité" },
            { sv: "brinna (brinner, brann, brunnit)", fr: "brûler" },
            { sv: "nerbrinna", fr: "brûler complètement" },
            { sv: "en gård, ar", fr: "ferme / cour" },
            { sv: "väl översatt", fr: "bien traduit" },
            { sv: "sy (3)", fr: "coudre" },
            { sv: "omkomma (er, kom, kommit)", fr: "mourir (accident)" },
            { sv: "hitta (1)", fr: "trouver" },
            { sv: "häkta (1)", fr: "arrêter, appréhender" },
            { sv: "första steget", fr: "premier pas/étape" },
            { sv: "hemskicka", fr: "envoyer chez eux" },
            { sv: "ett försök", fr: "tentative" },
            { sv: "ett trapphus", fr: "cage d’escaliers" },
            { sv: "avslöja (1)", fr: "révéler, dévoiler" },
            { sv: "tålmodig", fr: "patient" },
            { sv: "stänga ute från", fr: "exclure" },
            { sv: "en myndighet, er", fr: "autorité" },
            { sv: "en orsak, er", fr: "cause" },
            { sv: "en säkerhet, er", fr: "sécurité" },
            { sv: "rymma (2)", fr: "échapper" },
            { sv: "lyckas", fr: "réussir" },
            { sv: "minska (1)", fr: "diminuer" },
            { sv: "sänka (2) / höja (2)", fr: "diminuer / augmenter" },
            { sv: "en skatt, er", fr: "impôts" },
            { sv: "påverka (1)", fr: "influencer" },
            { sv: "SJ", fr: "SNCB (Chemins de fer)" }
        ],
        "Livre d'exercices": [
            { sv: "en tomt, er", fr: "jardin" },
            { sv: "en bensin", fr: "essence" },
            { sv: "en hyra, or", fr: "loyer" },
            { sv: "nog", fr: "assez, suffisant" },
            { sv: "ändå", fr: "cependant, néanmoins" },
            { sv: "stökig", fr: "désordonné" },
            { sv: "en hylla, or", fr: "étagère" },
            { sv: "fixa (1)", fr: "ranger" },
            { sv: "ordentlig", fr: "convenable, attentif" },
            { sv: "ett bord, en", fr: "table" },
            { sv: "en duk, ar", fr: "nappe" },
            { sv: "mysig", fr: "douillet" },
            { sv: "en skylt, ar", fr: "enseigne, panneau" },
            { sv: "ett betyg, /", fr: "note" },
            { sv: "Tung", fr: "Lourd" },
            { sv: "Rädd", fr: "Effrayé" },
            { sv: "Enkel", fr: "Simple, facile" },
            { sv: "Lycklig", fr: "Heureux" },
            { sv: "Söt", fr: "Doux, gentil" },
            { sv: "Snäll", fr: "Gentil, aimable, obéissant" },
            { sv: "trycka på (2)", fr: "pousser presser (bouton)" },
            { sv: "ett paraply, er", fr: "parapluie" },
            { sv: "en boll, ar", fr: "balle, ballon" },
            { sv: "en grej, er", fr: "choses, affaires" },
            { sv: "en kjol, ar", fr: "jupe" },
            { sv: "ett linne", fr: "débardeur" },
            { sv: "en mugg, ar", fr: "mug" },
            { sv: "mena (1)", fr: "vouloir dire" },
            { sv: "dröja (2)", fr: "hésiter, tarder" },
            { sv: "Väldig", fr: "Immense" },
            { sv: "Färsk", fr: "Doux, frais" },
            { sv: "lyxig", fr: "Luxueux" },
            { sv: "Laglig", fr: "Légal, légitime" },
            { sv: "Drygt", fr: "Un peu plus que" },
            { sv: "Pyttelite", fr: "Un mini peu" },
            { sv: "Lagom", fr: "Suffisant, approprié, juste ce qu’il faut" },
            { sv: "Tillräckligt", fr: "Suffisamment" },
            { sv: "För mycket", fr: "Trop" },
            { sv: "Knappt", fr: "Un peu moins que" },
            { sv: "Precis", fr: "Exactement" },
            { sv: "Ungefär", fr: "Environ" },
            { sv: "spola (1)", fr: "laver, rincer" },
            { sv: "längta (1)", fr: "aspirer à, languir, regretter" },
            { sv: "stirra (1)", fr: "regarder, fixer des yeux" },
            { sv: "klappa (1)", fr: "caresser, applaudir" },
            { sv: "tjata (1)", fr: "harceler" },
            { sv: "skaffa (1)", fr: "acquérir, procurer" },
            { sv: "allvarlig", fr: "important, grave, sérieux" },
            { sv: "en sjukdom, ar", fr: "maladie" },
            { sv: "smutsa (1)", fr: "salir" },
            { sv: "lämna mig ifred", fr: "fiche-moi la paix" },
            { sv: "skrämma", fr: "effrayer, intimider" },
            { sv: "har kontroll över/koll på", fr: "avoir le contrôle" },
            { sv: "sedan dess = efter det", fr: "depuis lors" },
            { sv: "locka (1)", fr: "attirer, leurrer" },
            { sv: "arg", fr: "en colère, fâché" },
            { sv: "stöta (stöter, stötte, stött) på", fr: "rencontrer/tomber sur qqn par hasard" },
            { sv: "en brottare", fr: "lutteur, catcheur" },
            { sv: "utöva (1)", fr: "exercer, pratiquer" },
            { sv: "rak", fr: "droit" },
            { sv: "böjd", fr: "courbé" },
            { sv: "en veckopeng", fr: "argent de poche" },
            { sv: "peka (1)", fr: "indiquer, montrer" },
            { sv: "hemsk", fr: "terrible, affreux, effrayant" },
            { sv: "trösta (1)", fr: "consoler" },
            { sv: "värka (2)", fr: "faire mal" },
            { sv: "följa efter (2)", fr: "suivre" },
            { sv: "ge sig iväg (ger, gav, gett)", fr: "partir" },
            { sv: "ge upp", fr: "abandonner" },
            { sv: "gå igenom", fr: "passer par, vérifier" },
            { sv: "hälsa på (1)", fr: "visiter, saluer" },
            { sv: "klättra upp (1)", fr: "monter" },
            { sv: "läsa igenom", fr: "finir de lire" },
            { sv: "skriva om", fr: "réécrire" },
            { sv: "släppa ut (2)", fr: "allonger, élargir (aussi laisser sortir)" },
            { sv: "spola ner (1)", fr: "jeter, balancer" },
            { sv: "svullna upp (1)", fr: "gonfler, enfler" },
            { sv: "ta hand om", fr: "s'occuper de" },
            { sv: "välja ut (2)", fr: "choisir, sélectionner" },
            { sv: "växa upp (2)", fr: "grandir" },
            { sv: "närma (1)", fr: "approcher" },
            { sv: "tacka (1)", fr: "remercier" },
            { sv: "ett nöje, n", fr: "plaisir" },
            { sv: "en makt, er", fr: "pouvoir" },
            { sv: "lösa (2)", fr: "résoudre" }
        ]
    }
};
