// ========================================
// Svenska Läraren - Vocabulary Data
// ========================================

const vocabularyData = {
    niveau2: {
        "Kapitel 10 - Natur & Geografi": [
            { sv: "en natur (er)", fr: "nature, environnement, paysage" },
            { sv: "en historia (er)", fr: "histoire" },
            { sv: "en ekonomi (er)", fr: "économie" },
            { sv: "en halvö (ar)", fr: "péninsule" },
            { sv: "en del (ar)", fr: "partie" },
            { sv: "ett landskap", fr: "paysage" },
            { sv: "olika", fr: "différent" },
            { sv: "platta", fr: "plat" },
            { sv: "en kustlinje (er)", fr: "littoral, ligne côtière" },
            { sv: "en sjö (ar)", fr: "lac" },
            { sv: "en skärgård (ar)", fr: "archipel" },
            { sv: "utanför", fr: "hors de, en dehors de, extérieur" },
            { sv: "en kust (er)", fr: "côte" },
            { sv: "tiotusentals", fr: "dizaines de milliers" },
            { sv: "Östersjön", fr: "mer baltique" },
            { sv: "en yta", fr: "surface, superficie" },
            { sv: "en tredjedel (ar)", fr: "un tiers" },
            { sv: "en befolkning (ar)", fr: "population" },
            { sv: "egen – eget – egna", fr: "propre (possession)" },
            { sv: "istid", fr: "période glacière" },
            { sv: "i norra", fr: "au nord de" },
            { sv: "i södra", fr: "au sud de" },
            { sv: "i norr", fr: "au nord" },
            { sv: "i söder", fr: "au sud" },
            { sv: "förut", fr: "auparavant, autrefois" },
            { sv: "fattig", fr: "pauvre, misérable, malheureux" },
            { sv: "en invandring (ar)", fr: "immigration" },
            { sv: "en flykting (ar)", fr: "réfugié" },
            { sv: "invandra (1)", fr: "immigrer" },
            { sv: "järn", fr: "fer" },
            { sv: "stål", fr: "acier" },
            { sv: "konstig", fr: "étrange, bizarre" },
            { sv: "en invånare", fr: "habitant" },
            { sv: "rik", fr: "riche" },
            { sv: "Jag kommer inte ihåg precis", fr: "je ne me souviens pas exactement" },
            { sv: "Jag tror att", fr: "je crois que" },
            { sv: "jag antar att", fr: "je suppose que" },
            { sv: "Det var en svår fråga", fr: "C’était une question difficile" },
            { sv: "Vänta, nu måste jag tänka lite", fr: "Attends, je dois un peu y réfléchir" },
            { sv: "Vad heter den/det/de (nu igen)?", fr: "Comment s’appelle (maintenant encore) ?" },
            { sv: "Hur många var det?", fr: "Combien il y en avait-il ?" },
            { sv: "Ja, det stämmer.", fr: "Oui c’est vrai" },
            { sv: "Ja, det är rätt.", fr: "Oui c’est vrai" },
            { sv: "Exakt!", fr: "Exact !" },
            { sv: "Nja, det är inte riktigt rätt.", fr: "Ce n'est pas vraiment correct." },
            { sv: "Nej, det är faktiskt fel.", fr: "C’est en fait faux." },
            { sv: "en författare", fr: "un écrivain" },
            { sv: "en politiker", fr: "un homme politique" },
            { sv: "en diplomat", fr: "un diplomate" },
            { sv: "en vetenskapsman", fr: "scientifique" },
            { sv: "en uppfinnare", fr: "inventeur" },
            { sv: "en popstjärna", fr: "pop star" },
            { sv: "en regissör (er)", fr: "réalisateur" },
            { sv: "en skådespelare / skådespelerska", fr: "acteur" },
            { sv: "ett helgon", fr: "saint" },
            { sv: "en idrottare", fr: "sportif" },
            { sv: "en operasångare / operasångerska", fr: "chanteur d’opéra" },
            { sv: "en drottning (ar)", fr: "reine" },
            { sv: "en utlänning (ar)", fr: "étranger" },
            { sv: "gullig", fr: "mignon, sympa" },
            { sv: "en flod (er)", fr: "fleuve, rivière" },
            { sv: "ett berg", fr: "montagne, mont" }
        ],
        "Kapitel 11 - Rencontres": [
            { sv: "En idé är att", fr: "une idée est de" },
            { sv: "Man kan prova att", fr: "On peut essayer de" },
            { sv: "Det bästa är kanske att...", fr: "Le mieux serait peut-être de" },
            { sv: "Där/Då kan man", fr: "Là/alors on peut" },
            { sv: "Ett bra sätt är att", fr: "Un bon moyen est de" },
            { sv: "gå ut med en hund", fr: "sortir le chien" },
            { sv: "ensam", fr: "seul" },
            { sv: "tipsa (1), rekommendera (1)", fr: "conseiller" },
            { sv: "stilig", fr: "beau, chic" },
            { sv: "ett tips", fr: "conseil" },
            { sv: "ett svar", fr: "réponse" },
            { sv: "ganska många", fr: "plutôt beaucoup" },
            { sv: "en dejtingsajt (er)", fr: "application de rencontres" },
            { sv: "lära sig (3)", fr: "apprendre" },
            { sv: "barnfri", fr: "sans enfants" },
            { sv: "härlig", fr: "magnifique" },
            { sv: "kul", fr: "cool" },
            { sv: "duktig i köket", fr: "doué en cuisine" },
            { sv: "X är inget för mig", fr: "X n’est pas pour moi" },
            { sv: "en rad (er)", fr: "ligne, rangée" },
            { sv: "ett meddelande", fr: "message" },
            { sv: "inte heller", fr: "pas non plus" },
            { sv: "en kram (ar)", fr: "câlin, étreinte" },
            { sv: "en sporthatare", fr: "qqn qui déteste le sport" },
            { sv: "en gård", fr: "une ferme" },
            { sv: "ett djur", fr: "animal" },
            { sv: "hit", fr: "ici (mouvement)" },
            { sv: "frånskild", fr: "séparé, divorcé" },
            { sv: "varannan", fr: "alterné, un sur deux" },
            { sv: "tvätta (1)", fr: "faire la lessive" },
            { sv: "stryka (stryker, strök, strukit)", fr: "repasser" },
            { sv: "leka (2)", fr: "jouer" },
            { sv: "förstås", fr: "bien entendu, évidemment" },
            { sv: "ett kök", fr: "cuisine (pièce)" },
            { sv: "nästa sommar", fr: "été prochain" },
            { sv: "Jag tycker om (att)…", fr: "J’aime..." },
            { sv: "Jag också/Det gör inter jag", fr: "Moi aussi/Moi pas" },
            { sv: "Jag kan…", fr: "Je peux..." },
            { sv: "Jag också/Det kan inte jag", fr: "Moi aussi/Moi pas" },
            { sv: "Jag tycker inte om (att) …", fr: "Je n’aime pas…" },
            { sv: "Inte jag heller/men det gör jag", fr: "Moi non plus/Moi si" },
            { sv: "Jan kan inte…", fr: "Je ne peux pas…" },
            { sv: "Inte jag heller/Men det kan jag", fr: "Moi non plus/Moi si" },
            { sv: "huslig", fr: "casanier" },
            { sv: "äventyrlig", fr: "aventurier" },
            { sv: "trevlig", fr: "sympa" },
            { sv: "arbetslös", fr: "sans emploi" },
            { sv: "manlig", fr: "viril" },
            { sv: "rolig", fr: "drôle" },
            { sv: "ointressant", fr: "inintéressant" },
            { sv: "töntig", fr: "stupide" },
            { sv: "tråkig", fr: "ennuyant" },
            { sv: "smart/klok/intelligent", fr: "intelligent" },
            { sv: "Det tycker jag också", fr: "Je pense aussi" },
            { sv: "Ja, han är perfekt!", fr: "Oui, c’est parfait" },
            { sv: "Absolut!", fr: "Absolument !" },
            { sv: "Bra idé", fr: "Bonne idée !" },
            { sv: "Jag håller med", fr: "Je suis d’accord" },
            { sv: "Nej, det tycker inte jag heller", fr: "Non, je ne pense pas non plus" },
            { sv: "Inte jag heller", fr: "Moi non plus" },
            { sv: "Ja, kanske, men är inte … bättre?", fr: "Oui, peut-être, mais…n'est pas mieux?" },
            { sv: "Nja, jag vet inte. Men … verkar bättre!", fr: "Eh bien, je ne sais pas. Mais ... semble mieux!" },
            { sv: "Va! Tycker du? Jag tycker att…", fr: "Tu crois/trouves? Je pense que…" },
            { sv: "ett tangentbord", fr: "clavier" },
            { sv: "en papperskorg (ar)", fr: "corbeille" },
            { sv: "en sladd (ar)/kabel (ar)", fr: "câble" },
            { sv: "kursiv stil", fr: "italique" },
            { sv: "spara (1)", fr: "sauvegarder" },
            { sv: "skriv ut", fr: "imprimer" },
            { sv: "ett snabel-a", fr: "@" },
            { sv: "en mapp (ar)", fr: "dossier" },
            { sv: "fet stil", fr: "gras" },
            { sv: "ett bindestreck", fr: "trait d’union" },
            { sv: "ångra (1)", fr: "annuler (regretter)" },
            { sv: "bifoga (1)", fr: "joindre (fichier)" },
            { sv: "en mus (möss, mössen)", fr: "souris" },
            { sv: "en punkt (er)", fr: "point" },
            { sv: "ett understreck", fr: "tiret bas/underscore" },
            { sv: "en skärm (ar)", fr: "écran" },
            { sv: "öppna (1)", fr: "ouvrir" },
            { sv: "ett utropstecken", fr: "point d’exclamation" },
            { sv: "ett frågetecken", fr: "point d’interrogation" },
            { sv: "ett snedstreck", fr: "slash" },
            { sv: "ett typsnitt", fr: "police (typographie)" },
            { sv: "söka (2)", fr: "chercher" },
            { sv: "klicka (1)", fr: "cliquer" },
            { sv: "logga in (1)", fr: "se connecter" },
            { sv: "ett virus", fr: "virus" },
            { sv: "ett lösenord", fr: "mot de passe" },
            { sv: "koppla (1)", fr: "brancher" },
            { sv: "sätta på", fr: "allumer" },
            { sv: "starta om (1)", fr: "redémarrer" },
            { sv: "en länk (ar)", fr: "un lien" },
            { sv: "fungera (1)", fr: "fonctionner" },
            { sv: "fylla på (2)", fr: "remplir, remettre (papier)" },
            { sv: "en hårddisk (ar)", fr: "disque dur" },
            { sv: "stänga av (1)", fr: "fermer, éteindre" },
            { sv: "ladda ner (1)", fr: "télécharger" },
            { sv: "stoppa in (1)", fr: "introduire, mettre" },
            { sv: "trasig", fr: "cassé, défectueux, pété" },
            { sv: "krascha (1)", fr: "planter (ordinateur)" },
            { sv: "en skrivare", fr: "imprimante" }
        ],
        "Kapitel 12 - Mat": [
            { sv: "en råvara", fr: "ingrédient" },
            { sv: "en vardagsmat", fr: "plat quotidien" },
            { sv: "en växt (er)", fr: "plante" },
            { sv: "dill", fr: "aneth" },
            { sv: "ett brännvin", fr: "eau-de-vie" },
            { sv: "en råg", fr: "seigle" },
            { sv: "ett nötkött", fr: "bœuf" },
            { sv: "en gryta", fr: "ragoût" },
            { sv: "inlagd i ättika", fr: "mariné dans le vinaigre" },
            { sv: "en lukt (er)", fr: "odeur" },
            { sv: "en smak (er)", fr: "goût, saveur" },
            { sv: "en lax (ar)", fr: "saumon" },
            { sv: "jordgubbar", fr: "fraises" },
            { sv: "en undersökning (ar)", fr: "sondage, enquête" },
            { sv: "få personer", fr: "quelques personnes" },
            { sv: "tillräcklig", fr: "suffisant, suffisamment" },
            { sv: "flesta", fr: "le plus" },
            { sv: "mörk choklad", fr: "chocolat noir" },
            { sv: "mjölkchoklad", fr: "chocolat au lait" },
            { sv: "en lök (ar)", fr: "oignon" },
            { sv: "pytt i panna", fr: "poêlée" },
            { sv: "kåldolmar", fr: "choux farcis" },
            { sv: "småkakor", fr: "petits biscuits" },
            { sv: "bjuda (bjuder, bjöd, bjudit)", fr: "inviter" },
            { sv: "fräsch", fr: "frais" },
            { sv: "en sparris (ar)", fr: "asperge" },
            { sv: "Det är fel att", fr: "Ce n’est pas bien de" },
            { sv: "en snabbmat", fr: "fast-food" },
            { sv: "På väg hem från", fr: "sur le chemin du retour de" },
            { sv: "en svamp (ar)", fr: "champignon" },
            { sv: "Jag är sugen på", fr: "J’ai envie de" },
            { sv: "skicka saltet (1)", fr: "passer le sel" },
            { sv: "smaka (1)", fr: "goûter, être bon" }
        ],
        "Kapitel 13 - Arbete": [
            { sv: "verka (1)", fr: "sembler, paraître" },
            { sv: "en kändis (ar)", fr: "célébrité" },
            { sv: "en översättare", fr: "traducteur" },
            { sv: "ledig", fr: "libre" },
            { sv: "stressig", fr: "stressant" },
            { sv: "är tvungen", fr: "être obligé de" },
            { sv: "skynda sig (1)", fr: "se dépêcher" },
            { sv: "duka (1)", fr: "mettre la table" },
            { sv: "ringa på dörren (2)", fr: "sonner à la porte" },
            { sv: "samtidigt", fr: "au même moment" },
            { sv: "toppjobb", fr: "poste clé" },
            { sv: "läkemedel", fr: "médicament" },
            { sv: "hämta (1)", fr: "aller chercher" },
            { sv: "lämna (1)", fr: "quitter, laisser, déposer" },
            { sv: "förskola", fr: "école maternelle" },
            { sv: "hushållsarbete", fr: "ménage" },
            { sv: "segla (1)", fr: "faire de la voile" },
            { sv: "försova sig", fr: "dormir trop longtemps, ne pas entendre son réveil" },
            { sv: "en affärsman", fr: "un homme d’affaires" },
            { sv: "var tvungen att", fr: "devoir (=måste)" },
            { sv: "ett möte", fr: "une réunion" },
            { sv: "ett labb", fr: "un laboratoire" },
            { sv: "hämtmat", fr: "plats à emporter" },
            { sv: "en gäst (er)", fr: "un hôte, un invité" },
            { sv: "ett huvudkontor", fr: "maison mère" },
            { sv: "viktig", fr: "important" },
            { sv: "ligga på topp", fr: "avoir un poste clé" },
            { sv: "vakna (1) / stiga (steg) upp", fr: "s’éveiller / se lever" },
            { sv: "gå och lägga sig", fr: "aller se coucher" },
            { sv: "en flygvärdinna", fr: "une hôtesse de l’air" },
            { sv: "landa (1)", fr: "atterrir" },
            { sv: "en pilot (-er)", fr: "pilote" },
            { sv: "ett (flyg)plan", fr: "un avion" },
            { sv: "servera (1)", fr: "servir" },
            { sv: "svara (1)", fr: "répondre" },
            { sv: "lyssna (1)", fr: "écouter" },
            { sv: "sitta och prata", fr: "être assis et parler" },
            { sv: "leka (2)", fr: "jouer (enfants)" },
            { sv: "läsa serier", fr: "lire des bandes dessinées" },
            { sv: "spela schack / damspel", fr: "jouer aux échecs/dames" },
            { sv: "ta ett bad", fr: "prendre un bain" },
            { sv: "somna (1)", fr: "s’endormir" },
            { sv: "sova (sover, sov, sovit)", fr: "dormir" },
            { sv: "skratta (1)", fr: "rire" },
            { sv: "ett bröllop", fr: "un mariage" },
            { sv: "en guide (er)", fr: "un guide touristique" },
            { sv: "en barnvakt (er)", fr: "baby-sitter" },
            { sv: "en simlärare", fr: "professeur de natation" },
            { sv: "simma (1)", fr: "nager" },
            { sv: "en snickare", fr: "un menuisier" },
            { sv: "en målare", fr: "un peintre" },
            { sv: "en trädgårdsmästare", fr: "jardinier" },
            { sv: "en fotograf (er)", fr: "photographe" },
            { sv: "en arkitekt (er)", fr: "architecte" },
            { sv: "en sjuksköterska", fr: "infirmière" },
            { sv: "en personlig tränare", fr: "coach personnel" },
            { sv: "en taxichaufför (er)", fr: "conducteur de taxi" },
            { sv: "en datasupporttekniker", fr: "informaticien" },
            { sv: "en bilmekaniker", fr: "mécanicien" },
            { sv: "händig", fr: "habile" },
            { sv: "modig", fr: "courageux" },
            { sv: "duktig på", fr: "bon en quelque chose" },
            { sv: "noggrann", fr: "minutieux, soigneux" },
            { sv: "omtänksam", fr: "attentif aux autres" },
            { sv: "stark", fr: "fort" },
            { sv: "teknisk", fr: "technique" },
            { sv: "pedagogisk", fr: "pédagogique" },
            { sv: "kreativ", fr: "créatif" },
            { sv: "social", fr: "social" },
            { sv: "trevlig", fr: "agréable, plaisant" },
            { sv: "ett körkort", fr: "un permis de conduire" },
            { sv: "fixa (1)", fr: "arranger, réparer" },
            { sv: "en idrott/sport", fr: "sport" },
            { sv: "en vetenskap", fr: "science" },
            { sv: "fota/fotografera", fr: "photo" },
            { sv: "naturligtvis", fr: "naturellement, bien entendu" }
        ],
        "Kapitel 14 - Fritid": [
            { sv: "utsikt över", fr: "avec vue sur" },
            { sv: "i gräset", fr: "dans l’herbe" },
            { sv: "en vila", fr: "repos" },
            { sv: "en frihet (er)", fr: "liberté" },
            { sv: "grilla (1)", fr: "faire un barbecue" },
            { sv: "åka båt (2)", fr: "faire du bateau" },
            { sv: "gå barfota", fr: "marcher pieds nus" },
            { sv: "plocka bär och svamp", fr: "cueillir des baies et des champignons" },
            { sv: "sola och bada (1)", fr: "bronzer et se baigner" },
            { sv: "vila (1)", fr: "se reposer" },
            { sv: "vara själv med familjen", fr: "être avec sa famille" },
            { sv: "spela kort med familjen", fr: "jouer aux cartes en famille" },
            { sv: "renovera huset (2)", fr: "rénover la maison" },
            { sv: "klippa gräs (2)", fr: "tondre" },
            { sv: "hugga ved", fr: "couper du bois" },
            { sv: "ha släktingar på långa besök", fr: "recevoir la famille pour de longs séjours" },
            { sv: "äta filmjölk och blåbär", fr: "manger du lait caillé et des myrtilles" },
            { sv: "jobbig", fr: "pénible" },
            { sv: "ett landställe", fr: "maison de campagne" },
            { sv: "äga", fr: "posséder, avoir" },
            { sv: "vanlig", fr: "habituel, ordinaire" },
            { sv: "jobba vid datorn", fr: "travailler sur le pc" },
            { sv: "undra om (1)", fr: "se demander si" },
            { sv: "en (bil)-färja", fr: "Ferry" },
            { sv: "en mås (ar)", fr: "mouette" },
            { sv: "ett grus", fr: "gravier, sable" },
            { sv: "glittra (1)", fr: "briller, étinceler" },
            { sv: "kliva ur bilen", fr: "sortir de la voiture" },
            { sv: "ett hjärta", fr: "cœur" },
            { sv: "skål", fr: "santé (boire)" },
            { sv: "ett dass", fr: "toilette" },
            { sv: "få lite ont i", fr: "ressentir une douleur à" },
            { sv: "lukta (1)", fr: "sentir (odeur)" },
            { sv: "sur", fr: "fâché, contrarié, sur" },
            { sv: "en paj (er)", fr: "tarte" },
            { sv: "en bastu (-r)", fr: "sauna" },
            { sv: "nervös", fr: "nerveux" },
            { sv: "lätt", fr: "facile, léger" },
            { sv: "tack för senast", fr: "merci pour la dernière fois" },
            { sv: "ta bort", fr: "enlever" },
            { sv: "behöver inte", fr: "ne pas devoir (måste inte)" },
            { sv: "ett bröllop", fr: "mariage" },
            { sv: "ett kalas", fr: "fête" },
            { sv: "en inflyttningsfest (er)", fr: "pendaison de crémaillère" },
            { sv: "Vi fixar", fr: "on s’occupe de" },
            { sv: "vi tänder grillarna", fr: "on allume le barbecue" },
            { sv: "en vigsel (ar)", fr: "cérémonie de mariage, noces" },
            { sv: "en önskelista", fr: "liste des cadeaux de mariage" },
            { sv: "tack för ikväll", fr: "merci pour ce soir" },
            { sv: "Ta för er!", fr: "Servez-vous" },
            { sv: "Det är bra för mig", fr: "J’ai assez merci" },
            { sv: "va?", fr: "N’est-ce pas ?" }
        ],
        "Kapitel 15 - Livsstil": [
            { sv: "skämta (1)", fr: "plaisanter, blaguer" },
            { sv: "kalla (1)", fr: "appeler, nommer" },
            { sv: "heter … i efternamn", fr: "avoir … pour nom de famille" },
            { sv: "hälften av", fr: "la moitié de" },
            { sv: "ett par", fr: "couple" },
            { sv: "i veckan", fr: "par semaine" },
            { sv: "tjock", fr: "gros, épais" },
            { sv: "jag minns inte", fr: "je ne me rappelle pas" },
            { sv: "Varför då?", fr: "Pourquoi donc ?" },
            { sv: "tyst", fr: "silencieux" },
            { sv: "ett prat", fr: "conversation" },
            { sv: "vandra (1)", fr: "se promener, faire une randonnée" },
            { sv: "ett mål", fr: "but, objectif" },
            { sv: "en by (ar)", fr: "village" },
            { sv: "verkar vara", fr: "semble être" },
            { sv: "en sten (ar)", fr: "pierre" },
            { sv: "ensamma", fr: "seul" },
            { sv: "en bit (ar)", fr: "morceau, partie" },
            { sv: "från dag till dag", fr: "d’un jour à l’autre" },
            { sv: "ett mörk", fr: "obscurité" },
            { sv: "innan", fr: "avant (que)" },
            { sv: "deppig", fr: "déprimé" },
            { sv: "fulla av", fr: "rempli de" },
            { sv: "verka (1)", fr: "sembler" },
            { sv: "ingen/någon", fr: "personne, quelqu’un" },
            { sv: "inget/något", fr: "rien, quelque chose" },
            { sv: "fast", fr: "bien que" },
            { sv: "Det beror på", fr: "Cela dépend de" },
            { sv: "betyda (2)", fr: "signifier" },
            { sv: "en kropp (ar)", fr: "corps" },
            { sv: "bomull", fr: "coton" },
            { sv: "ull", fr: "laine" },
            { sv: "tunn", fr: "mince, fin" },
            { sv: "räcker", fr: "suffire" },
            { sv: "en svett", fr: "sueur" },
            { sv: "skydda (1)", fr: "protéger" },
            { sv: "röra (3)", fr: "bouger" },
            { sv: "torr", fr: "sec" },
            { sv: "en vante (vantar)", fr: "gant" }
        ],
        "Kapitel 16 - Skola & Utbildning": [
            { sv: "ett lov", fr: "congé" },
            { sv: "en termin (er)", fr: "semestre, trimestre" },
            { sv: "en föreläsning (ar)", fr: "cours magistral" },
            { sv: "en rast (er)", fr: "pause" },
            { sv: "ett seminarium", fr: "séminaire" },
            { sv: "en grundskola", fr: "école primaire" },
            { sv: "gymnasiet", fr: "lycée" },
            { sv: "ett universitet", fr: "université" },
            { sv: "Komvux", fr: "promotion sociale" },
            { sv: "ett betyg", fr: "note, évaluation" },
            { sv: "ett ämne", fr: "matière (scolaire)" },
            { sv: "1 till 9", fr: "1 à 9" },
            { sv: "en väg (ar)", fr: "chemin" },
            { sv: "en utbildning (ar)", fr: "éducation, enseignement" },
            { sv: "en plugghäst (ar)", fr: "tête, personne intelligente" },
            { sv: "fokusera (1)", fr: "se concentrer" },
            { sv: "duktig", fr: "bon, capable" },
            { sv: "skolka (1)", fr: "sécher les cours" },
            { sv: "räkna (1)", fr: "compter" },
            { sv: "småtråkig", fr: "un peu ennuyeux" },
            { sv: "är färdig med", fr: "en avoir fini avec" },
            { sv: "en gata", fr: "rue" },
            { sv: "en andra chans", fr: "une seconde chance" },
            { sv: "framtiden", fr: "l'avenir" },
            { sv: "ett fast jobb", fr: "emploi fixe" },
            { sv: "forska (1)", fr: "faire de la recherche" },
            { sv: "en praktik (er)", fr: "stage" },
            { sv: "om + temps", fr: "dans X temps" },
            { sv: "då", fr: "alors, à ce moment-là" },
            { sv: "först", fr: "d'abord" },
            { sv: "sedan", fr: "ensuite" },
            { sv: "efter det", fr: "ensuite" },
            { sv: "vara färdig med något", fr: "avoir terminé quelque chose" },
            { sv: "fortsätta", fr: "continuer" },
            { sv: "söka (2) (efter/till)", fr: "chercher/postuler" },
            { sv: "leta (1) efter", fr: "chercher pour trouver" },
            { sv: "hitta (1)", fr: "trouver" },
            { sv: "frilansa (1)", fr: "travailler en freelance" },
            { sv: "examen", fr: "diplôme" },
            { sv: "börsmäklare", fr: "courtier, trader" },
            { sv: "tuff", fr: "dur, difficile" }
        ],
        "Kapitel 17 - Boende": [
            { sv: "en bostad", fr: "logement, habitation" },
            { sv: "en villa", fr: "maison" },
            { sv: "en förort (er)", fr: "banlieue" },
            { sv: "strax utanför", fr: "juste à côté" },
            { sv: "en bostadsrätt (er)", fr: "logement en copropriété" },
            { sv: "en hyreslägenhet (er)", fr: "appartement loué" },
            { sv: "hyr (3)", fr: "louer (locataire)" },
            { sv: "hyr ut", fr: "louer (propriétaire)" },
            { sv: "en tvättstuga", fr: "buanderie" },
            { sv: "en öppen spis (ar)", fr: "feu ouvert" },
            { sv: "elda (1)", fr: "faire du feu" },
            { sv: "inomhus", fr: "à l’intérieur" },
            { sv: "i bra skick", fr: "en bon état" },
            { sv: "en tomt (er)", fr: "jardin, cour, terrain" },
            { sv: "sambo", fr: "concubin" },
            { sv: "mambo", fr: "tanguy" },
            { sv: "är särbo", fr: "être en couple sans habiter ensemble" },
            { sv: "hyra en lägenhet i andra hand", fr: "sous-louer un appartement" },
            { sv: "månadsavgift", fr: "cotisation mensuelle" },
            { sv: "ett renoveringsobjekt", fr: "à rénover" },
            { sv: "en balkong (er)", fr: "balcon" },
            { sv: "kakelugn", fr: "poêle en faïence" },
            { sv: "vanligtvis", fr: "habituellement" },
            { sv: "en kokvrå", fr: "coin cuisine" },
            { sv: "en toalett (er)", fr: "toilette" },
            { sv: "vissa", fr: "certains, quelque" },
            { sv: "ett förråd", fr: "débarras" },
            { sv: "en vind (ar)", fr: "grenier" },
            { sv: "en källare", fr: "cave" },
            { sv: "gemensam", fr: "commun" },
            { sv: "ett radhus", fr: "maison de rangée" },
            { sv: "ett parhus", fr: "maison mitoyenne" },
            { sv: "hemma i mitt hus", fr: "à ma maison" },
            { sv: "ett studentrum", fr: "chambre étudiant" },
            { sv: "en andrahandslägenhet", fr: "appartement sous-loué" },
            { sv: "i närförort", fr: "près des banlieues" },
            { sv: "på pendlingsavstånd", fr: "à une bonne distance pour faire la navette" },
            { sv: "i kollektiv", fr: "en collocation" },
            { sv: "inneboende", fr: "chez l’habitant" }
        ],
        "Moodle & Textes": [
            { sv: "inte längre = inte mer", fr: "ne… plus" },
            { sv: "hända (händer, hände, hänt)", fr: "se passer, arriver" },
            { sv: "medan", fr: "pendant que" },
            { sv: "bege sig", fr: "se rendre" },
            { sv: "rak (raka vägen)", fr: "Droit (le droit chemin)" },
            { sv: "en matros (-er)", fr: "un matelot" },
            { sv: "en panna (-or)", fr: "un front (aussi poêle)" },
            { sv: "en apa (apor)", fr: "un singe" },
            { sv: "en kappsäck", fr: "un sac de voyage" },
            { sv: "full med", fr: "rempli de" },
            { sv: "guldpengar", fr: "pièces d’or" },
            { sv: "stadig", fr: "solide, ferme" },
            { sv: "gå stadigt", fr: "marcher d’un pas ferme" },
            { sv: "utan att", fr: "sans (faire quelque chose)" },
            { sv: "vända sig om", fr: "se retourner" },
            { sv: "märkvärdig", fr: "remarquable, étrange" },
            { sv: "en tår", fr: "une larme" },
            { sv: "stark", fr: "fort" },
            { sv: "en polis (-er)", fr: "un policier" },
            { sv: "lyfta (2)", fr: "soulever" },
            { sv: "en häst (-ar)", fr: "un cheval" },
            { sv: "utan vidare", fr: "sans plus, tout bonnement" },
            { sv: "ett fritidshus / sommarstuga", fr: "maison de campagne" },
            { sv: "utsikt över", fr: "vue sur" },
            { sv: "hav (-et)", fr: "mer" },
            { sv: "granne (-n, -ar)", fr: "voisin" },
            { sv: "gå barfota", fr: "marcher à pieds nus" },
            { sv: "en vila", fr: "repos" },
            { sv: "glad", fr: "content, joyeux" },
            { sv: "lycklig", fr: "heureux" },
            { sv: "på landet", fr: "à la campagne" },
            { sv: "hugga ved", fr: "couper du bois" },
            { sv: "en släkting", fr: "parent" },
            { sv: "stanna (1)", fr: "rester" },
            { sv: "bråka (1)", fr: "se disputer" },
            { sv: "ett läge", fr: "situation" },
            { sv: "uteplats", fr: "terrasse" },
            { sv: "avstånd", fr: "distance" },
            { sv: "en inbjudan", fr: "une invitation" },
            { sv: "ännu", fr: "encore" },
            { sv: "undra (1)", fr: "demander" },
            { sv: "lakan", fr: "draps" },
            { sv: "titta efter", fr: "chercher du regard" },
            { sv: "skrika (skriker, skrek, skrikit)", fr: "crier" },
            { sv: "kvar", fr: "qui reste" },
            { sv: "färjeläge", fr: "embarcadère" },
            { sv: "grusväg", fr: "chemin de terre" },
            { sv: "glittra (1)", fr: "scintiller" },
            { sv: "ur", fr: "hors de" },
            { sv: "ett dass", fr: "toilette sèche" },
            { sv: "tvätta sig", fr: "se laver" },
            { sv: "snöre", fr: "cordon" },
            { sv: "dra (drar, drog, dragit)", fr: "tirer" },
            { sv: "ont", fr: "mal" },
            { sv: "kantarell", fr: "chanterelle" },
            { sv: "ställe", fr: "endroit" },
            { sv: "sur", fr: "fâché" },
            { sv: "älgstek", fr: "rôti d’élan" },
            { sv: "skjuta (skjuter, sköt, skjutit)", fr: "tirer (arme)" },
            { sv: "frysa (fryser, frös, frusit)", fr: "geler" },
            { sv: "naken", fr: "nu" },
            { sv: "smulpaj", fr: "crumble" },
            { sv: "vetemjöl", fr: "farine de blé" },
            { sv: "matsked", fr: "cuiller à soupe" },
            { sv: "potatismjöl", fr: "fécule" },
            { sv: "blanda (1)", fr: "mélanger" },
            { sv: "en skål", fr: "saladier" },
            { sv: "en form", fr: "moule" },
            { sv: "en deg", fr: "pâte" },
            { sv: "ljummen", fr: "tiède" },
            { sv: "grädda (1)", fr: "cuire au four" },
            { sv: "en ugn", fr: "four" },
            { sv: "en klänning", fr: "robe" },
            { sv: "före", fr: "avant" },
            { sv: "glömma (2)", fr: "oublier" },
            { sv: "dra hemåt", fr: "rentrer chez soi" },
            { sv: "vett och etikett", fr: "code de bonne conduite" },
            { sv: "bjuden på", fr: "invité à" },
            { sv: "ytterskor", fr: "chaussures d’extérieur" },
            { sv: "inneskor", fr: "chaussures d’intérieur" },
            { sv: "ta på / ta av", fr: "mettre / retirer (vêtements)" },
            { sv: "knytis", fr: "auberge espagnole" },
            { sv: "tända (2)", fr: "allumer" },
            { sv: "brännboll", fr: "jeu de balle suédois" },
            { sv: "mot", fr: "contre/vers" },
            { sv: "vigsel", fr: "bénédiction" },
            { sv: "äga rum", fr: "avoir lieu" },
            { sv: "danssko", fr: "chaussure de danse" },
            { sv: "nyfödd", fr: "nouveau-né" },
            { sv: "gammpojken", fr: "vieux garçon" },
            { sv: "förr", fr: "autrefois" },
            { sv: "växa upp", fr: "grandir" },
            { sv: "sluttning", fr: "pente" },
            { sv: "trähus", fr: "maison de bois" },
            { sv: "förvånad", fr: "étonné" },
            { sv: "i alla fall", fr: "en tous cas" },
            { sv: "ett moln", fr: "nuage" },
            { sv: "sväva (1)", fr: "planer" },
            { sv: "en trappa", fr: "escalier" },
            { sv: "ett dragspel", fr: "accordéon" },
            { sv: "känna sig", fr: "se sentir" },
            { sv: "tung / lätt", fr: "lourd / léger" },
            { sv: "ett öde", fr: "destin" },
            { sv: "hustru", fr: "épouse" },
            { sv: "lycka", fr: "bonheur" },
            { sv: "vemodig", fr: "mélancolique" },
            { sv: "braka loss", fr: "se mettre à barder" },
            { sv: "buller", fr: "vacarme" },
            { sv: "vrål", fr: "hurlement" },
            { sv: "brödkavel", fr: "rouleau à pâtisserie" },
            { sv: "odugling", fr: "incapable" },
            { sv: "latmask", fr: "fainéant" },
            { sv: "suput", fr: "ivrogne" },
            { sv: "helst", fr: "de préférence" },
            { sv: "dö på fläcken", fr: "mourir sur place" },
            { sv: "blind", fr: "aveugle" },
            { sv: "fly (3)", fr: "fuir" },
            { sv: "rida", fr: "chevaucher" },
            { sv: "enligt", fr: "selon" },
            { sv: "egentligen", fr: "en fait" },
            { sv: "skilja sig", fr: "se séparer" },
            { sv: "vård", fr: "soins" },
            { sv: "kaka", fr: "gâteau" },
            { sv: "bulle", fr: "brioche" },
            { sv: "snacka (1)", fr: "bavarder" },
            { sv: "mest", fr: "surtout" },
            { sv: "ägg", fr: "oeuf" },
            { sv: "vara dubbelbokad", fr: "avoir un conflit horaire" },
            { sv: "söka någon", fr: "chercher à atteindre quelqu’un" },
            { sv: "försäkringskassa", fr: "mutuelle" },
            { sv: "föräldrapenning", fr: "allocations familiales" },
            { sv: "tanke", fr: "pensée" },
            { sv: "märka (2)", fr: "remarquer" },
            { sv: "prat", fr: "bavardage" },
            { sv: "småprata", fr: "parler de tout et de rien" },
            { sv: "medlem", fr: "membre" },
            { sv: "skön", fr: "agréable" },
            { sv: "nicka (1)", fr: "approuver" },
            { sv: "klättra (1)", fr: "grimper" },
            { sv: "berg", fr: "montagne" },
            { sv: "verka (1)", fr: "sembler" },
            { sv: "nöjd", fr: "content" },
            { sv: "en bit ifrån", fr: "à une certaine distance" },
            { sv: "ljus", fr: "lumière" },
            { sv: "mörker", fr: "obscurité" },
            { sv: "längta efter", fr: "avoir très envie de" },
            { sv: "sucka (1)", fr: "soupirer" },
            { sv: "gå mot", fr: "aller vers" },
            { sv: "midsommar", fr: "solstice d’été" },
            { sv: "verkligen", fr: "vraiment" },
            { sv: "hoppas", fr: "espérer" },
            { sv: "deppig av", fr: "déprimé" },
            { sv: "siffra", fr: "chiffre" },
            { sv: "använda", fr: "utiliser" },
            { sv: "personnummer", fr: "numéro national" },
            { sv: "badplats", fr: "lieu de baignade" },
            { sv: "beställa (2)", fr: "commander" },
            { sv: "både och", fr: "les deux à la fois" },
            { sv: "dygn", fr: "24h" },
            { sv: "mild", fr: "doux" },
            { sv: "bero på", fr: "dépendre de" },
            { sv: "ostadig", fr: "instable" },
            { sv: "påstående", fr: "affirmation" },
            { sv: "lager", fr: "couche" },
            { sv: "springa", fr: "courir" },
            { sv: "svettig", fr: "en sueur" },
            { sv: "stilla", fr: "tranquille" },
            { sv: "fot", fr: "pied" },
            { sv: "hand", fr: "main" },
            { sv: "huvud", fr: "tête" },
            { sv: "mage", fr: "ventre" },
            { sv: "rumpa", fr: "postérieur" },
            { sv: "svettas", fr: "transpirer" },
            { sv: "mössa", fr: "bonnet" },
            { sv: "minnas / komma ihåg", fr: "se souvenir" },
            { sv: "föremål", fr: "objet" },
            { sv: "lekställning", fr: "portique de jeux" },
            { sv: "rutschbana", fr: "toboggan" },
            { sv: "studsmatta", fr: "trampoline" },
            { sv: "leksak", fr: "jouet" },
            { sv: "gå sönder", fr: "se casser" },
            { sv: "bänk", fr: "banc" },
            { sv: "väntsal", fr: "salle d’attente" },
            { sv: "julgran", fr: "sapin de noël" },
            { sv: "juldag", fr: "jour de noël" },
            { sv: "anslagstavla", fr: "tableau d’affichage" },
            { sv: "försenad", fr: "en retard" },
            { sv: "inställd", fr: "annulé" },
            { sv: "trist / sorglig", fr: "triste (événement)" },
            { sv: "ledsen", fr: "triste (personne)" },
            { sv: "åker", fr: "champ" },
            { sv: "yxa", fr: "hache" },
            { sv: "döda (1)", fr: "tuer" },
            { sv: "Godkänd", fr: "Approuvé, réussi" },
            { sv: "Välja", fr: "Choisir" },
            { sv: "Populär", fr: "Apprécié" },
            { sv: "Fordon", fr: "Véhicule" },
            { sv: "Vanlig >< ovanlig", fr: "Courant >< rare" },
            { sv: "Låna (1)", fr: "Emprunter" },
            { sv: "Låna ut", fr: "Prêter" },
            { sv: "Lån", fr: "Emprunt" },
            { sv: "Examen", fr: "Examen final" },
            { sv: "pluggis", fr: "bûcheur" },
            { sv: "lära", fr: "apprendre (à qqn)" },
            { sv: "lära sig", fr: "apprendre (à soi)" },
            { sv: "tonåring", fr: "adolescent" },
            { sv: "matte", fr: "math" },
            { sv: "samhällskunskap", fr: "sciences sociales" },
            { sv: "trivas", fr: "se plaire" },
            { sv: "sträng", fr: "sévère" },
            { sv: "ta studenten", fr: "passer l'examen final" },
            { sv: "vara sugen på", fr: "avoir très envie de" },
            { sv: "masterexamen", fr: "diplôme de master" },
            { sv: "gå ut nian", fr: "terminer la 9ème" },
            { sv: "hoppa av", fr: "arrêter en cours" },
            { sv: "verkstad", fr: "atelier" },
            { sv: "läsa in", fr: "rattraper" },
            { sv: "andra", fr: "deuxième" },
            { sv: "värst", fr: "pire" },
            { sv: "fiskkorv", fr: "saucisse de poisson" },
            { sv: "blek", fr: "pâle" },
            { sv: "se ut som", fr: "ressembler à" },
            { sv: "mos", fr: "purée" },
            { sv: "hitta på", fr: "inventer" },
            { sv: "påhitt", fr: "invention" },
            { sv: "matpåhitt", fr: "créations culinaires" },
            { sv: "se dagens ljus", fr: "voir le jour" },
            { sv: "för övrigt", fr: "par ailleurs" },
            { sv: "tant", fr: "dame" },
            { sv: "mattant", fr: "dame de cantine" },
            { sv: "tvinga (1)", fr: "forcer" },
            { sv: "äta upp", fr: "finir son assiette" },
            { sv: "utveckla (1)", fr: "développer" },
            { sv: "spotta (1)", fr: "cracher" },
            { sv: "märkas", fr: "se remarquer" },
            { sv: "ficka", fr: "poche" },
            { sv: "följd", fr: "conséquence" },
            { sv: "lukt", fr: "odeur" },
            { sv: "följa med", fr: "accompagner" },
            { sv: "plåga", fr: "peine, torture" },
            { sv: "i stort sett", fr: "en gros" },
            { sv: "ätare", fr: "mangeur" },
            { sv: "välja", fr: "choisir" },
            { sv: "vara ensam om", fr: "être le seul à" },
            { sv: "eftermiddagshem", fr: "garderie" },
            { sv: "ordna (1)", fr: "organiser" },
            { sv: "enbart", fr: "seulement" },
            { sv: "ung", fr: "jeune" },
            { sv: "hata (1)", fr: "détester" },
            { sv: "messmör", fr: "pâte à tartiner au petit lait" }
        ],
        "Livre d'exercices": [
            { sv: "Jag har mycket att göra", fr: "j’ai beaucoup à faire" },
            { sv: "ett prov", fr: "examen" },
            { sv: "pigg", fr: "actif, en forme" },
            { sv: "en fiol", fr: "violon" },
            { sv: "vacker", fr: "beau" },
            { sv: "sätta på", fr: "se mettre à son ordinateur" },
            { sv: "trött på", fr: "fatigué de" },
            { sv: "sitter vid datorn", fr: "être devant le pc" },
            { sv: "bjuda på", fr: "inviter à" },
            { sv: "dricka till maten", fr: "boire avec le repas" },
            { sv: "annorlunda", fr: "autrement, différent" },
            { sv: "en grädde", fr: "crème fraîche" },
            { sv: "bara", fr: "seulement, juste" },
            { sv: "en åsikt", fr: "opinion" },
            { sv: "en värdering", fr: "estimation" },
            { sv: "sent", fr: "tard" },
            { sv: "ett väder", fr: "temps, météo" },
            { sv: "se ut", fr: "avoir l’air" },
            { sv: "ledsen", fr: "triste" },
            { sv: "hålla", fr: "tenir, garder" },
            { sv: "köa (1)", fr: "faire la queue" },
            { sv: "en fåtölj", fr: "fauteuil" },
            { sv: "vänta i regnet", fr: "attendre sous la pluie" },
            { sv: "rekommendera", fr: "recommander" },
            { sv: "en krydda", fr: "épice" },
            { sv: "en staty", fr: "statue" },
            { sv: "ett slott", fr: "château" },
            { sv: "turister", fr: "touristes" },
            { sv: "odla (1)", fr: "cultiver" },
            { sv: "annars", fr: "sinon, autrement" },
            { sv: "förrgår", fr: "avant-hier" },
            { sv: "är duktig att", fr: "être doué en" },
            { sv: "ett möte", fr: "réunion" },
            { sv: "ringa på dörren", fr: "sonner à la porte" },
            { sv: "ett huvud", fr: "chef" },
            { sv: "dejta på nätet", fr: "faire des rencontres en ligne" },
            { sv: "bjuda", fr: "inviter, offrir" },
            { sv: "passa (1)", fr: "convenir" },
            { sv: "låna (1)", fr: "emprunter" },
            { sv: "lämna tillbaka", fr: "rendre" },
            { sv: "långt", fr: "loin" },
            { sv: "länge", fr: "longtemps" },
            { sv: "hur långt?", fr: "quelle distance ?" },
            { sv: "hur länge?", fr: "depuis combien de temps ?" },
            { sv: "stilig", fr: "stylé, élégant" },
            { sv: "en massa", fr: "beaucoup" },
            { sv: "ett bröllop", fr: "mariage" },
            { sv: "tåget är försenat/inställt", fr: "le train est en retard/annulé" },
            { sv: "slumpen bestämmer", fr: "le destin décide" },
            { sv: "desperat", fr: "désespéré" },
            { sv: "en matlagningskurs", fr: "cours de cuisine" },
            { sv: "fuska (1)", fr: "tricher" },
            { sv: "frisk", fr: "en bonne santé" },
            { sv: "lugn", fr: "calme" },
            { sv: "en sömn", fr: "sommeil" },
            { sv: "släppa (2)", fr: "lâcher" },
            { sv: "för länge sedan", fr: "il y a longtemps" },
            { sv: "svara mig", fr: "réponds-moi" },
            { sv: "jag bara undrar", fr: "je me demande juste" },
            { sv: "försvinna", fr: "disparaître" },
            { sv: "igen", fr: "de nouveau, encore" },
            { sv: "ett krig", fr: "guerre" },
            { sv: "hemlagat", fr: "fait maison" },
            { sv: "en korg", fr: "panier" },
            { sv: "en vagn", fr: "chariot" },
            { sv: "ägg", fr: "œufs" },
            { sv: "en nöt", fr: "noix" },
            { sv: "en kassa", fr: "caisse" },
            { sv: "betala kontant", fr: "payer en cash" },
            { sv: "koka (1)", fr: "cuire à l’eau" },
            { sv: "steka (2)", fr: "cuire à la poêle" },
            { sv: "baka (1)", fr: "cuire au four" },
            { sv: "en dill", fr: "aneth" },
            { sv: "ett skal", fr: "carapace" },
            { sv: "en havre", fr: "avoine" },
            { sv: "ett vete", fr: "blé" },
            { sv: "vispa (1)", fr: "fouetter" },
            { sv: "blåbär", fr: "myrtilles" },
            { sv: "hjortron", fr: "mûres des marais" },
            { sv: "björnbär", fr: "mûres" },
            { sv: "hallon", fr: "framboises" },
            { sv: "en tårta", fr: "gâteau" },
            { sv: "en glass", fr: "glace" },
            { sv: "pannkakor", fr: "crêpes" },
            { sv: "inte heller", fr: "pas non plus" },
            { sv: "inte alls", fr: "pas du tout" },
            { sv: "allergisk mot", fr: "allergique à" },
            { sv: "en sparris", fr: "asperge" },
            { sv: "nöttunga", fr: "langue de bœuf" },
            { sv: "gissa (1)", fr: "deviner" },
            { sv: "en bio", fr: "cinéma" },
            { sv: "ett knytis", fr: "repas" },
            { sv: "skrika", fr: "crier" },
            { sv: "väldig", fr: "très, énorme" },
            { sv: "rita (1)", fr: "dessiner" },
            { sv: "nöjd med", fr: "content de" },
            { sv: "tom", fr: "vide" },
            { sv: "en skriva", fr: "tranche" },
            { sv: "är på semester", fr: "être en vacances" },
            { sv: "snusa (1)", fr: "consommer du tabac" },
            { sv: "hälla (2)", fr: "verser" },
            { sv: "hälsa på", fr: "rendre visite" },
            { sv: "bakom", fr: "derrière" },
            { sv: "finns det?", fr: "y a-t-il ?" },
            { sv: "den här", fr: "ceci" },
            { sv: "klara ett prov", fr: "réussir l’examen" },
            { sv: "stänga", fr: "fermer" }
        ],
        "Autre": [
            { sv: "blanda (1)", fr: "mélanger" },
            { sv: "kolsyrat vatten", fr: "eau pétillante" },
            { sv: "krama (1)", fr: "faire une accolade" },
            { sv: "en kram", fr: "accolade" },
            { sv: "en kyss", fr: "bise" },
            { sv: "i stället för", fr: "à la place de" },
            { sv: "ett ljus", fr: "lumière" },
            { sv: "jag antar att", fr: "je suppose que" },
            { sv: "Jo", fr: "si (réponse positive à question négative)" },
            { sv: "ett hjul", fr: "roue" },
            { sv: "en häxa", fr: "sorcière" },
            { sv: "kikärter", fr: "pois chiches" },
            { sv: "bland annat", fr: "entre autres" },
            { sv: "en tång", fr: "algue" },
            { sv: "valla (1)", fr: "guider" },
            { sv: "en fart", fr: "vitesse" },
            { sv: "ett mål", fr: "but" },
            { sv: "första ögonkastet", fr: "au premier regard" },
            { sv: "i början", fr: "au début" },
            { sv: "varandra", fr: "l’un l’autre" },
            { sv: "färdig", fr: "prêt, fini" },
            { sv: "en saga", fr: "conte" },
            { sv: "mittre", fr: "milieu" },
            { sv: "mittemot", fr: "en face de" },
            { sv: "knapp", fr: "à peine" },
            { sv: "byta jobb", fr: "changer de travail" }
        ]
    }
};
